import React,{useState} from 'react';
import {Link,useNavigate,useSearchParams} from 'react-router-dom';
import {LockKeyhole,LogIn,Eye,EyeOff} from 'lucide-react';
import {useApp} from './context.jsx';
import {ErrorBox,Loading} from './components.jsx';
export function AuthGate({children}){const {config,canEdit,v4}=useApp();if(!config)return <Loading/>;return canEdit?children:<section className="access-panel surface"><LockKeyhole size={38}/><h1>{v4.auth.authRequired}</h1><p>{v4.auth.readOnly}</p><Link className="btn primary" to="/login">{v4.auth.login}<LogIn size={18}/></Link></section>;}
export default function Login(){const {v4,signIn,canEdit,selectedDistrict}=useApp(),a=v4.auth,[email,setEmail]=useState(''),[password,setPassword]=useState(''),[visible,setVisible]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(null),navigate=useNavigate(),[params]=useSearchParams();
 async function submit(e){e.preventDefault();setBusy(true);setError(null);try{await signIn(email,password);setPassword('');const next=params.get('next');navigate(next&&next.startsWith('/')&&!next.startsWith('//')?next:'/district/'+selectedDistrict);}catch(e){setError(e);}finally{setBusy(false);}}
 return <div className="auth-layout"><section className="auth-art"><img src="/images/astana-concept.jpg" alt="Astana City Lab"/><div><span>AKIM</span><h2>{v4.district.workspace}</h2><p>{a.roleNote}</p></div></section><section className="auth-form surface"><LockKeyhole size={32}/><h1>{a.title}</h1><p>{a.description}</p>{canEdit?<Link className="btn primary" to={'/district/'+selectedDistrict}>{v4.district.workspace}</Link>:<form onSubmit={submit}><label htmlFor="login-email">{a.email}</label><input id="login-email" type="email" autoComplete="username" required maxLength={150} value={email} onChange={e=>setEmail(e.target.value)}/><label htmlFor="login-password">{a.password}</label><div className="password-field"><input id="login-password" type={visible?'text':'password'} autoComplete="current-password" required maxLength={256} value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" aria-label={visible?a.hidePassword:a.showPassword} onClick={()=>setVisible(!visible)}>{visible?<EyeOff size={18}/>:<Eye size={18}/>}</button></div>{error&&<ErrorBox error={error}/>}<button className="btn primary full" disabled={busy}>{busy?a.signingIn:a.login}<LogIn size={18}/></button></form>}</section></div>;
}

