import React,{useEffect,useRef} from 'react';
import {Link,NavLink,useLocation} from 'react-router-dom';
import {ArrowUpRight,ArrowRight,Building2,Map,Layers3,FolderOpen,Trophy,BookOpen,Menu,X,Bus,TreePine,HeartPulse,ShieldCheck,Wrench,LogIn,CheckCircle2,Info} from 'lucide-react';
import {useApp} from './context.jsx';
import {METRICS,CATEGORIES} from '../../shared/data.mjs';
export const ICONS={transport:Bus,ecology:TreePine,social:HeartPulse,safety:ShieldCheck,services:Wrench};
export const COLORS={transport:'#3c70c1',ecology:'#178364',social:'#a267a5',safety:'#c88b37',services:'#388da0'};
export function CategoryIcon({id,size=19}){const Icon=ICONS[id];return <Icon size={size}/>;}
export function Layout({children}){
 const {locale,setLocale,t,copy,config}=useApp(),[menu,setMenu]=React.useState(false),location=useLocation();
 useEffect(()=>{setMenu(false);window.scrollTo({top:0,behavior:'instant'});},[location.pathname]);
 const routes=[['/',copy.nav.home],['/map',copy.nav.map],['/simulator',copy.nav.simulation],['/scenarios',copy.nav.scenarios],['/leaderboard',copy.nav.leaderboard]];
 return <><a className="skip" href="#main">{t('continue')}</a><header className="site-header"><Link to="/" className="logo"><span className="logo-shape"><Building2 size={25}/></span><span>AKIM<small>Astana City Lab</small></span></Link><nav className={menu?'is-open':''} aria-label={t('navigation')}>{routes.map(([path,name])=><NavLink key={path} to={path} end={path==='/'}>{name}</NavLink>)}</nav><div className="header-tools"><div className="language-switch" aria-label={t('language')}>{['kk','ru','en'].map(l=><button key={l} aria-pressed={l===locale} onClick={()=>setLocale(l)}>{l==='kk'?'ҚАЗ':l.toUpperCase()}</button>)}</div><Link className="profile-link" to="/scenarios" aria-label={t('myScenarios')}><FolderOpen size={20}/></Link><button className="mobile-menu icon-button" aria-label={t('menu')} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header><main id="main" className="page">{children}</main><footer className="site-footer"><Link to="/" className="footer-brand">AKIM <span>{t('footer')}</span></Link><div><Link to="/methodology">{copy.nav.methodology}</Link><a href="https://github.com/BAITC-Hacks/hack-314bbb86-triangle" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={14}/></a></div></footer></>;
}
export function PageHead({eyebrow,title,description,actions}){return <div className="page-head"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{actions&&<div className="head-actions">{actions}</div>}</div>;}
export function MetricGrid({district}){const {data,number}=useApp();return <div className="metrics">{Object.entries(METRICS).map(([key,meta])=><div className="metric" key={key}><div><span>{data.metrics[key]}</span><b className={district.metrics[key]<40?'danger':''}>{number(district.metrics[key])}{district.deltas?.[key]!==0&&district.deltas?.[key]!=null&&<small>{district.deltas[key]>0?'+':''}{number(district.deltas[key])}</small>}</b></div><div className="track"><i style={{width:`${district.metrics[key]}%`,background:COLORS[meta.category]}}/></div></div>)}</div>;}
export function Notice({children}){return <div className="notice"><Info size={18}/><p>{children}</p></div>;}
export function Empty({title,text,children}){return <div className="empty"><span><Layers3 size={35}/></span><h2>{title}</h2><p>{text}</p>{children}</div>;}
export function Loading(){const {t}=useApp();return <div className="loading" role="status"><span className="spinner"/>{t('loading')}</div>;}
export function ErrorBox({error,retry}){const {t}=useApp();return <div className="error-box" role="alert">{t(error?.message)===(error?.message)?t('ERROR'):t(error?.message||'ERROR')}{retry&&<button className="btn secondary" onClick={retry}>{t('retry')}</button>}</div>;}
export function SignIn(){const {t}=useApp();return <Empty title={t('signIn')} text={t('signInNote')}><a className="btn primary" href="/signin-with-chatgpt?return_to=/scenarios" target="_top"><LogIn size={18}/>{t('signIn')}</a></Empty>;}
export function Modal({title,onClose,children}){const ref=useRef(),{t}=useApp();useEffect(()=>{const d=ref.current;d.showModal();const fn=e=>{e.preventDefault();onClose();};d.addEventListener('cancel',fn);return()=>{d.removeEventListener('cancel',fn);d.close();};},[]);return <dialog ref={ref} className="modal" onClick={e=>{if(e.target===ref.current)onClose();}}><div className="modal-heading"><h2>{title}</h2><button className="icon-button" aria-label={t('cancel')} onClick={onClose}><X size={22}/></button></div>{children}</dialog>;}

