import React,{useEffect,useRef} from 'react';
import {Link,NavLink,useLocation} from 'react-router-dom';
import {ArrowUpRight,ArrowRight,Building2,Map,Layers3,FolderOpen,Trophy,BookOpen,Menu,X,Bus,TreePine,HeartPulse,ShieldCheck,Wrench,LayoutDashboard,BriefcaseBusiness,Landmark,CheckCircle2,Info,ChevronsUpDown,Sparkles} from 'lucide-react';
import {useApp} from './context.jsx';
import {METRICS,CATEGORIES} from '../../shared/data.mjs';
import {FUTURES_COPY} from './futures-copy.mjs';
import {WHATIF_COPY} from './whatif-copy.mjs';
export const ICONS={transport:Bus,ecology:TreePine,social:HeartPulse,safety:ShieldCheck,services:Wrench};
export const COLORS={transport:'#3c70c1',ecology:'#178364',social:'#a267a5',safety:'#c88b37',services:'#388da0'};
export function CategoryIcon({id,size=19}){const Icon=ICONS[id];return <Icon size={size}/>;}
export function Layout({children}){
 const {locale,setLocale,t,copy,config,role,setRole,office,decisions}=useApp(),[menu,setMenu]=React.useState(false),[roles,setRoles]=React.useState(false),location=useLocation();
 useEffect(()=>{setMenu(false);window.scrollTo({top:0,behavior:'instant'});},[location.pathname]);
 const routes=[['/',office.dashboard,LayoutDashboard],['/map',copy.nav.map,Map],['/simulator',office.detailedPlan,Layers3],['/advisor',WHATIF_COPY[locale].title,Sparkles],['/vision',FUTURES_COPY[locale].beforeAfter,Building2],['/presentation',FUTURES_COPY[locale].generatedDeck,BookOpen],['/scenarios',copy.nav.scenarios,FolderOpen],['/leaderboard',copy.nav.leaderboard,Trophy]];
 const current=routes.find(([path])=>path==='/'?location.pathname==='/':location.pathname.startsWith(path));const RoleIcon=role==='mayor'?Landmark:BriefcaseBusiness;
 return <div className="office-app"><a className="skip" href="#main">{t('continue')}</a>{menu&&<button className="nav-scrim" aria-label={t('cancel')} onClick={()=>setMenu(false)}/>}<aside className={`office-sidebar ${menu?'is-open':''}`}><Link to="/" className="office-logo"><span><Building2 size={26}/></span><b>AKIM<small>Astana City Lab</small></b></Link><button className="office-role" onClick={()=>setRoles(true)}><RoleIcon size={21}/><span><small>{office.currentRole}</small><b>{office[role]}</b></span><ChevronsUpDown size={15}/></button><nav aria-label={t('navigation')}>{routes.map(([path,name,Icon])=><NavLink key={path} to={path} end={path==='/'}><Icon size={19}/><span>{name}</span>{path==='/simulator'&&<small>{decisions.length}/5</small>}</NavLink>)}</nav><div className="office-sidebar-bottom"><Link to="/methodology"><BookOpen size={18}/>{copy.nav.methodology}</Link><div className="office-environment"><span className="live-dot"/><span>{office.simulationMode}<small>{office.fixedConditions}</small></span></div><p>Triangle<br/><span>Astana Innovations</span></p></div></aside><div className="office-main"><header className="office-topbar"><div className="office-breadcrumb"><button className="mobile-menu icon-button" aria-label={t('menu')} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><span>{office.workspace}</span><span className="breadcrumb-separator">/</span><b>{current?.[1]||t('method')}</b></div><div className="header-tools"><span className="office-ai-status"><Sparkles size={14}/>{office.aiReady}</span><div className="language-switch" aria-label={t('language')}>{['kk','ru','en'].map(l=><button key={l} aria-pressed={l===locale} onClick={()=>setLocale(l)}>{l==='kk'?'ҚАЗ':l.toUpperCase()}</button>)}</div><button className="office-avatar" aria-label={office.switchRole} onClick={()=>setRoles(true)}><RoleIcon size={18}/></button></div></header><main id="main" className="page office-page">{children}</main><footer className="office-footer"><span>{office.simulationMode} · {t('footer')}</span><a href="https://github.com/BAITC-Hacks/hack-314bbb86-triangle" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={13}/></a></footer></div>{roles&&<Modal title={office.chooseRole} onClose={()=>setRoles(false)}><div className="role-options">{[['mayor',Landmark],['manager',BriefcaseBusiness]].map(([id,Icon])=><button key={id} aria-pressed={id===role} onClick={()=>{setRole(id);setRoles(false);}}><Icon size={26}/><span><b>{office[id]}</b><small>{office[id+'Description']}</small></span>{role===id&&<CheckCircle2 size={20}/>}</button>)}</div><p className="role-note">{office.roleNote}</p></Modal>}</div>;
}
export function PageHead({eyebrow,title,description,actions}){return <div className="page-head"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{actions&&<div className="head-actions">{actions}</div>}</div>;}
export function MetricGrid({district}){const {data,number}=useApp();return <div className="metrics">{Object.entries(METRICS).map(([key,meta])=><div className="metric" key={key}><div><span>{data.metrics[key]}</span><b className={district.metrics[key]<40?'danger':''}>{number(district.metrics[key])}{district.deltas?.[key]!==0&&district.deltas?.[key]!=null&&<small>{district.deltas[key]>0?'+':''}{number(district.deltas[key])}</small>}</b></div><div className="track"><i style={{width:`${district.metrics[key]}%`,background:COLORS[meta.category]}}/></div></div>)}</div>;}
export function Notice({children}){return <div className="notice"><Info size={18}/><p>{children}</p></div>;}
export function Empty({title,text,children}){return <div className="empty"><span><Layers3 size={35}/></span><h2>{title}</h2><p>{text}</p>{children}</div>;}
export function Loading(){const {t}=useApp();return <div className="loading" role="status"><span className="spinner"/>{t('loading')}</div>;}
export function ErrorBox({error,retry}){const {t}=useApp();return <div className="error-box" role="alert">{t(error?.message)===(error?.message)?t('ERROR'):t(error?.message||'ERROR')}{retry&&<button className="btn secondary" onClick={retry}>{t('retry')}</button>}</div>;}
export function WorkspaceStatus(){const {config,refreshConfig,t}=useApp();return !config?<Loading/>:<ErrorBox error={new Error('WORKSPACE_UNAVAILABLE')} retry={refreshConfig}/>;}
export function Modal({title,onClose,children}){const ref=useRef(),{t}=useApp();useEffect(()=>{const d=ref.current;d.showModal();const fn=e=>{e.preventDefault();onClose();};d.addEventListener('cancel',fn);return()=>{d.removeEventListener('cancel',fn);d.close();};},[]);return <dialog ref={ref} className="modal" onClick={e=>{if(e.target===ref.current)onClose();}}><div className="modal-heading"><h2>{title}</h2><button className="icon-button" aria-label={t('cancel')} onClick={onClose}><X size={22}/></button></div>{children}</dialog>;}


