import React,{lazy,Suspense,useState,useEffect} from 'react';
import {Link,useParams,useSearchParams} from 'react-router-dom';
import {Plus,Trash2,Play,Pause,Presentation as PresentationIcon,MapPin,Clock3,Sparkles,ArrowRight} from 'lucide-react';
import {useApp} from './context.jsx';
import {PageHead,CategoryIcon,COLORS,Notice,Loading} from './components.jsx';
import {DISTRICTS,MEASURES,CATEGORIES} from '../../shared/data.mjs';
import {validate} from '../../shared/engine.mjs';
import {districtFacts,districtIdOrDefault} from '../../shared/district.mjs';
import {QuarterChart} from './ForecastCharts.jsx';
import Presentation from './Presentation.jsx';
const StreetScene=lazy(()=>import('./StreetScene.jsx'));
export default function District(){
 const {id}=useParams(),[params,setParams]=useSearchParams(),{selectedDistrict,setSelectedDistrict,decisions,setDecisions,t,v4,data,number,locale,canEdit,errorText,office}=useApp();
 const districtId=districtIdOrDefault(id||params.get('district')||selectedDistrict),tab=['plan','report'].includes(params.get('tab'))?params.get('tab'):'vision';
 const [quarter,setQuarter]=useState(8),[playing,setPlaying]=useState(true),[category,setCategory]=useState('all');
 useEffect(()=>{setSelectedDistrict(districtId);setQuarter(8);},[districtId]);
 const facts=districtFacts(decisions,districtId,quarter),finalFacts=districtFacts(decisions,districtId),labels={kk:{index:'Аудан индексі',selected:'Аудандағы жобалар',empty:'Жоба қосқанда көрініс осы жерде өзгереді.',now:'Қазір',plan:'Жоспардан кейін',add:'Қосу',remove:'Алып тастау',elsewhere:'Басқа ауданда таңдалған',draft:'Бес шешімге дейінгі алдын ала есеп',quarter:'Тоқсан',clear:'Жоспарды тазарту'},ru:{index:'Индекс района',selected:'Проекты в районе',empty:'Добавьте проект: изменения появятся в этой сцене.',now:'Сейчас',plan:'После реализации',add:'Добавить',remove:'Убрать',elsewhere:'Выбрано в другом районе',draft:'Предварительный расчёт до пяти решений',quarter:'Квартал',clear:'Очистить план'},en:{index:'District index',selected:'Projects in this district',empty:'Add a project to see the change in this scene.',now:'Now',plan:'After delivery',add:'Add',remove:'Remove',elsewhere:'Selected in another district',draft:'Provisional until five decisions',quarter:'Quarter',clear:'Clear plan'}}[locale];
 function choose(m){if(!canEdit)return;const existing=decisions.find(d=>d.measureId===m.id);if(existing){setDecisions(decisions.filter(d=>d.measureId!==m.id));return;}const next=[...decisions,m.scope==='city'?{measureId:m.id}:{measureId:m.id,districtId}];if(validate(next,{partial:true}).valid){setDecisions(next);setQuarter(8);}}
 const openTab=key=>setParams(key==='vision'?{}:{tab:key});
 return <div className="district-workspace"><div className="district-switcher" aria-label={t('district')}>{DISTRICTS.map(d=><Link className={d.id===districtId?'active':''} to={'/district/'+d.id+(tab==='vision'?'':'?tab='+tab)} key={d.id}><MapPin size={15}/>{data.districts[d.id].name}</Link>)}</div><PageHead title={data.districts[districtId].name} description={data.districts[districtId].profile} actions={<Link className="btn secondary" to={'/map?district='+districtId}><MapPin size={17}/>{t('goMap')}</Link>}/><div className="district-workbar"><div className="district-mode-tabs" role="tablist">{[['vision',v4.district.beforeAfter],['plan',v4.district.planning],['report',v4.district.presentation]].map(([key,label])=><button key={key} role="tab" aria-selected={tab===key} onClick={()=>openTab(key)}>{key==='report'&&<PresentationIcon size={17}/>} {label}</button>)}</div><div className="district-treasury"><span>{v4.district.sharedBudget}</span><b>{facts.city.cost}<small> / 100</small></b><span>{decisions.length}/5</span></div></div>
 {tab==='report'?<Presentation districtId={districtId} embedded/>:<><div className="district-scene-grid"><section className="district-scene-panel"><div className="district-scene-toolbar"><div className="segmented"><button aria-pressed={quarter===0} onClick={()=>setQuarter(0)}>{t('before')}</button><button aria-pressed={quarter===8} onClick={()=>setQuarter(8)}>{t('after')}</button></div><span>{labels.quarter} Q{quarter}</span><button className="icon-button" onClick={()=>setPlaying(!playing)} aria-label={playing?({kk:'Кідірту',ru:'Пауза',en:'Pause'})[locale]:({kk:'Ойнату',ru:'Воспроизвести',en:'Play'})[locale]}>{playing?<Pause size={18}/>:<Play size={18}/>}</button></div><div className="district-stage"><Suspense fallback={<Loading/>}><StreetScene key={districtId} decisions={decisions} districtId={districtId} quarter={quarter} playing={playing} label={data.districts[districtId].name+' · 3D'} trafficChange={facts.after.metrics.T1-facts.before.metrics.T1}/></Suspense><div className="district-scene-label"><MapPin size={15}/>{data.districts[districtId].name}<span>{quarter===0?labels.now:labels.plan}</span></div></div><div className="district-time"><label htmlFor="district-quarter">{labels.quarter} <b>Q{quarter} / Q8</b></label><input id="district-quarter" type="range" min="0" max="8" step="1" value={quarter} onChange={e=>setQuarter(Number(e.target.value))}/></div><p className="district-scene-note">{v4.settings[districtId]}</p></section><aside className="district-live-panel"><span className="eyebrow">{labels.index}</span><div className="district-score-pair"><strong>{number(facts.before.score)}</strong><ArrowRight size={22}/><strong>{number(facts.after.score)}</strong></div><p>{decisions.length===5?office.quarters:labels.draft}</p><div className="district-key-metrics">{['T1','S1','E1','B1','C1'].map(key=><div key={key}><span>{data.metrics[key]}</span><b>{number(facts.before.metrics[key])}<ArrowRight size={13}/>{number(facts.after.metrics[key])}</b><div className="dual-track"><i style={{width:facts.before.metrics[key]+'%'}}/><i style={{width:facts.after.metrics[key]+'%',background:COLORS[({T1:'transport',S1:'social',E1:'ecology',B1:'safety',C1:'services'})[key]]}}/></div></div>)}</div><button className="btn primary full" onClick={()=>openTab('report')}><PresentationIcon size={17}/>{v4.district.reportTitle}</button></aside></div>
 <section className="district-project-strip"><div><h2>{labels.selected}</h2><p>{finalFacts.measures.length?'Q8 · '+v4.district.impactTitle:labels.empty}</p></div><div>{finalFacts.measures.map(m=><div className="district-project-chip" key={m.id}><CategoryIcon id={m.category} size={17}/><span>{data.measures[m.id].name}<small>{m.scope==='city'?t('whole'):data.districts[districtId].name} · {m.cost}/100 · Q{m.lag+1}</small></span>{canEdit&&<button className="icon-button" aria-label={labels.remove+' '+data.measures[m.id].name} onClick={()=>choose(m)}><Trash2 size={16}/></button>}</div>)}</div></section>
 {!canEdit?<Notice><span>{v4.auth.readOnly} </span><Link to={'/login?next='+encodeURIComponent('/district/'+districtId)}>{v4.auth.login}</Link></Notice>:<section className="district-catalog"><div className="section-title"><h2>{v4.district.addMeasure}</h2><Link className="text-link" to={'/advisor?district='+districtId}><Sparkles size={17}/>AI</Link></div><div className="category-tabs"><button className={category==='all'?'active':''} onClick={()=>setCategory('all')}>{t('all')}</button>{CATEGORIES.map(c=><button className={category===c.id?'active':''} key={c.id} onClick={()=>setCategory(c.id)}><CategoryIcon id={c.id} size={16}/>{data.categories[c.id]}</button>)}</div><div className="district-measure-grid">{MEASURES.filter(m=>category==='all'||m.category===category).map(m=>{const chosen=decisions.find(d=>d.measureId===m.id),local=chosen&&(!chosen.districtId||chosen.districtId===districtId),next=[...decisions,m.scope==='city'?{measureId:m.id}:{measureId:m.id,districtId}],check=validate(next,{partial:true});return <article className={'district-measure '+(local?'chosen':'')} key={m.id}><div><span className="category-symbol" style={{color:COLORS[m.category],background:COLORS[m.category]+'15'}}><CategoryIcon id={m.category}/></span><b>{m.cost}<small> /100</small></b></div><h3>{data.measures[m.id].name}</h3><p>{data.measures[m.id].description}</p><small>{m.scope==='city'?t('whole'):data.districts[districtId].name} · <Clock3 size={13}/> Q{m.lag+1}</small><div className="district-measure-effects">{Object.entries(m.effects).map(([key,value])=><span key={key}>{data.metrics[key]} <b className={value<0?'danger':''}>{value>0?'+':''}{number(value*(8-m.lag)/8)}</b></span>)}</div><button className={local?'btn secondary full':'btn primary full'} disabled={!local&&(!!chosen||!check.valid)} onClick={()=>choose(m)}>{local?<Trash2 size={15}/>:<Plus size={15}/>} {local?labels.remove:chosen?labels.elsewhere:labels.add}</button>{!chosen&&!check.valid&&<p className="blocked">{errorText(check.errors[0])}</p>}</article>;})}</div></section>}
 <section className="surface district-trajectory"><h2>{v4.district.impactTitle}</h2><QuarterChart series={finalFacts.series} title={labels.index+' · '+data.districts[districtId].name}/></section><Notice>{v4.district.sceneNote}</Notice></>}
 </div>;
}

