// Future scenes are illustrations; numerical forecasts come from the engine.
export const FUTURES_COPY = {
  kk: {
    futureView: 'Ауданның болашақ көрінісі',
    projectedQuarter: 'Болжамды тоқсан',
    illustrationOnly: 'AI жасаған тұжырымдамалық иллюстрация',
    noRealCounts: 'Көріністегі адамдар мен көліктер саны нақты статистикаға немесе есептік болжамға жатпайды.',
    district: 'Аудан',
    beforeAfter: 'Дейін және кейін',
    playPause: 'Анимацияны ойнату немесе кідірту',
    play: 'Ойнату',
    pause: 'Кідірту',
    generatedDeck: 'Сценарий презентациясы',
    downloadPptx: 'PowerPoint жүктеу',
    downloadHtml: 'HTML есебін жүктеу',
    nextQuarter: 'Келесі тоқсанға ұсыныстар',
    AIallocation: 'AI арқылы жоспар құру',
    explainAllocation: 'AI бюджет бөлінісін ұсынады, есептеу моделі құны мен әсерін тексереді. Қолданар алдында жоспарды қарап шығыңыз.',
    officialContext: 'Ресми дереккөздердегі контекст',
    contextNote: 'Ресми жаңалықтар қосымша контекст береді. Барлығына ортақ синтетикалық деректер мен Score есебі өзгермейді.',
    slides: [
      'Сценарий және негізгі нәтиже',
      'Бес шешім және бюджет',
      'Аудандардағы күтілетін өзгерістер',
      'Көрсеткіштер мен шаралардың үлесі',
      'Тәуекелдер және таңдау салдары',
      'Келесі тоқсанның іс-қимыл жоспары',
    ],
  },
  ru: {
    futureView: 'Будущий облик района',
    projectedQuarter: 'Прогнозный квартал',
    illustrationOnly: 'Концептуальная иллюстрация, созданная AI',
    noRealCounts: 'Количество людей и машин в сцене не является реальной статистикой или расчётным прогнозом.',
    district: 'Район',
    beforeAfter: 'До и после',
    playPause: 'Воспроизвести или приостановить анимацию',
    play: 'Воспроизвести',
    pause: 'Приостановить',
    generatedDeck: 'Презентация сценария',
    downloadPptx: 'Скачать PowerPoint',
    downloadHtml: 'Скачать HTML-отчёт',
    nextQuarter: 'Рекомендации на следующий квартал',
    AIallocation: 'Составить план с AI',
    explainAllocation: 'AI предлагает распределение бюджета, расчётная модель проверяет стоимость и влияние. Просмотрите план перед применением.',
    officialContext: 'Контекст из официальных источников',
    contextNote: 'Официальные новости дают дополнительный контекст. Общие для всех синтетические данные и расчёт Score остаются неизменными.',
    slides: [
      'Сценарий и основной результат',
      'Пять решений и бюджет',
      'Ожидаемые изменения по районам',
      'Показатели и вклад мероприятий',
      'Риски и компромиссы',
      'План действий на следующий квартал',
    ],
  },
  en: {
    futureView: 'A district’s future appearance',
    projectedQuarter: 'Projected quarter',
    illustrationOnly: 'AI-generated concept illustration',
    noRealCounts: 'The people and vehicles shown do not represent actual statistics or calculated forecasts.',
    district: 'District',
    beforeAfter: 'Before and after',
    playPause: 'Play or pause animation',
    play: 'Play',
    pause: 'Pause',
    generatedDeck: 'Scenario presentation',
    downloadPptx: 'Download PowerPoint',
    downloadHtml: 'Download HTML report',
    nextQuarter: 'Recommendations for next quarter',
    AIallocation: 'Build a plan with AI',
    explainAllocation: 'AI proposes a budget allocation. The calculation model checks its cost and impact. Review the plan before applying it.',
    officialContext: 'Context from official sources',
    contextNote: 'Official news provides additional context. The shared synthetic dataset and Score calculation remain unchanged.',
    slides: [
      'Scenario and headline result',
      'Five decisions and the budget',
      'Expected changes by district',
      'Indicators and measure contributions',
      'Risks and trade-offs',
      'Next quarter’s action plan',
    ],
  },
};
