import React,{lazy,Suspense,useState,useEffect,useRef} from 'react';
import {Link} from 'react-router-dom';
import {ArrowRight,ArrowUpRight,Wallet,ChartNoAxesCombined,AlertTriangle,ListChecks,MapPin,Plus,Sparkles,Landmark,BriefcaseBusiness,Check,Clock3} from 'lucide-react';
import {useApp} from './context.jsx';
import {BASELINE,calculate} from '../../shared/engine.mjs';
import {MEASURES,CATEGORIES,EXAMPLE} from '../../shared/data.mjs';
import {FUTURES_COPY} from './futures-copy.mjs';
import {CategoryIcon,COLORS} from './components.jsx';
const CityScene=lazy(()=>import('./CityScene.jsx'));
function NumberValue({value}){const {number}=useApp(),[visible,setVisible]=useState(value),previous=useRef(value);useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches){setVisible(value);previous.current=value;return;}let frame,start;const from=previous.current;function animate(time){start??=time;const t=Math.min((time-start)/650,1),eased=1-(1-t)**3;setVisible(from+(value-from)*eased);if(t<1)frame=requestAnimationFrame(animate);else previous.current=value;}frame=requestAnimationFrame(animate);return()=>cancelAnimationFrame(frame);},[value]);return number(visible);}
export default function Home(){
 const {t,office,role,data,number,decisions,setDecisions,locale,canEdit,selectedDistrict:selected,setSelectedDistrict:setSelected}=useApp(),[after,setAfter]=useState(true);
 const forecast=calculate(decisions),result=after?forecast:BASELINE,district=result.districts.find(d=>d.id===selected),low=Object.entries(district.metrics).sort((a,b)=>a[1]-b[1]).slice(0,3),RoleIcon=role==='mayor'?Landmark:BriefcaseBusiness;
 const allocation=CATEGORIES.map(c=>({...c,cost:decisions.reduce((sum,d)=>{const m=MEASURES.find(m=>m.id===d.measureId);return sum+(m.category===c.id?m.cost:0)},0)}));
 return <div className="dashboard"><div className="desk-heading"><div><span className="desk-role"><RoleIcon size={16}/>{office[role]}</span><h1>{office[role+'Title']}</h1><p>{office[role+'Subtitle']}</p></div><div className="desk-heading-actions"><div className="planning-horizon"><Clock3 size={17}/><span>{office.period}<b>{office.quarters}</b></span></div><Link className="btn primary" to={decisions.length===5?'/simulator?review=1':'/simulator'}>{decisions.length===5?<Sparkles size={17}/>:<Plus size={17}/>} {decisions.length===5?office.viewResults:office.addDecision}</Link></div></div>
 <div className="desk-stats"><article className="treasury-stat"><div className="desk-stat-label"><Wallet size={17}/>{office.budget}<span>100</span></div><div className="desk-stat-value"><strong>{forecast.remaining}</strong><span>{office.remainingBudget}</span></div><div className="treasury-bar">{allocation.map(c=><i key={c.id} style={{width:c.cost+'%',background:COLORS[c.id]}}/>)}</div><small>{office.used}: {forecast.cost} / 100</small></article><article><div className="desk-stat-label"><ChartNoAxesCombined size={17}/>{office.qualityScore}</div><div className="desk-stat-value"><strong><NumberValue value={forecast.score}/></strong><span className="stat-gain">+{number(forecast.score-BASELINE.score)}</span></div><small>{decisions.length===5?office.scoreNote:office.provisional}</small></article><article><div className="desk-stat-label"><AlertTriangle size={17}/>{office.needsAttention}</div><div className="desk-stat-value"><strong>{forecast.critical.length.toString().padStart(2,'0')}</strong><span>{office.indicators}</span></div><small>{forecast.critical.length?data.districts[forecast.weakest.id].name:office.noCritical}</small></article><article><div className="desk-stat-label"><ListChecks size={17}/>{office.draft}</div><div className="desk-stat-value"><strong>{decisions.length}<em>/5</em></strong><span>{office.planned}</span></div><div className="decision-progress">{[0,1,2,3,4].map(i=><span className={i<decisions.length?'filled':''} key={i}>{i<decisions.length?<Check size={10}/>:i+1}</span>)}</div></article></div>
 <section className="desk-atlas"><div className="atlas-heading"><div><h2>{office.exploreMap}</h2><span>{office.quarters} · {office.provisional}</span></div><div className="segmented"><button aria-pressed={!after} onClick={()=>setAfter(false)}>{office.before}</button><button aria-pressed={after} onClick={()=>setAfter(true)}>{office.after}</button></div></div><div className="atlas-content"><div className="atlas-map"><Suspense fallback={<div className="scene-loading"><span className="spinner"/>{office.loadingCity}</div>}><CityScene districts={result.districts} selected={selected} onSelect={setSelected}/></Suspense><p className="atlas-caption"><MapPin size={13}/>{office.mapHeight}</p></div><aside className="atlas-district"><div className="district-kicker"><MapPin size={15}/>{office.districtProfile}</div><div className="atlas-district-name"><h2>{data.districts[selected].name}</h2><strong>{number(district.score)}<small>QoL / 100</small></strong></div><p>{data.districts[selected].profile}</p><h3>{office.lowest}</h3><div className="priority-metrics">{low.map(([key,value])=><div key={key}><span>{data.metrics[key]}<b className={value<40?'danger':''}>{number(value)}</b></span><div><i style={{width:value+'%',background:value<40?'#c87852':'#6297a4'}}/><em/></div></div>)}</div><Link className="btn primary full" to={`/district/${selected}`}>{office.detailedPlan}<ArrowRight size={17}/></Link><div className="atlas-district-selector">{result.districts.map(d=><button aria-pressed={d.id===selected} onClick={()=>setSelected(d.id)} key={d.id}>{data.districts[d.id].name}</button>)}</div></aside></div></section>
 <section className="city-concept-banner"><div><span className="eyebrow">ASTANA / CITY VISION</span><h2>{FUTURES_COPY[locale].futureView}</h2><p>{FUTURES_COPY[locale].explainAllocation}</p><div className="head-actions"><Link className="btn primary" to="/advisor?allocate=1"><Sparkles size={16}/>{FUTURES_COPY[locale].AIallocation}</Link><Link className="btn secondary" to={`/district/${selected}`}>{FUTURES_COPY[locale].beforeAfter}<ArrowUpRight size={16}/></Link></div></div><figure><img src="/images/astana-concept.jpg" alt={FUTURES_COPY[locale].illustrationOnly} loading="lazy"/><figcaption>{FUTURES_COPY[locale].illustrationOnly}</figcaption></figure></section> {role==='mayor'?<div className="desk-bottom"><section className="desk-panel district-ranking"><div className="desk-section-head"><h2>{office.districtRanking}</h2><Link to="/map">{t('goMap')}<ArrowUpRight size={16}/></Link></div>{[...forecast.districts].sort((a,b)=>a.score-b.score).map((d,i)=><button key={d.id} onClick={()=>setSelected(d.id)} aria-pressed={selected===d.id}><span className="ranking-index">{i+1}</span><span className="ranking-name">{data.districts[d.id].name}<small>{Math.round(d.population*100)}% {t('population').toLowerCase()}</small></span><span className="ranking-track"><i style={{width:d.score+'%'}}/></span><b>{number(d.score)}</b><ArrowUpRight size={15}/></button>)}</section><section className="desk-panel allocation-panel"><div className="desk-section-head"><h2>{office.allocation}</h2><span>{forecast.cost}/100</span></div>{allocation.map(c=><div key={c.id}><CategoryIcon id={c.id} size={17}/><span>{data.categories[c.id]}</span><div><i style={{width:c.cost+'%',background:COLORS[c.id]}}/></div><b>{c.cost}</b></div>)}<Link to="/simulator" className="text-link">{office.openPlan}<ArrowRight size={16}/></Link></section></div>:<section className="desk-panel planning-panel"><div className="desk-section-head"><h2>{office.planningDirections}</h2><span>{data.districts[selected].name}</span></div><div className="planning-categories">{CATEGORIES.map(c=><Link to={`/simulator?district=${selected}&category=${c.id}`} key={c.id}><span style={{color:COLORS[c.id],background:COLORS[c.id]+'12'}}><CategoryIcon id={c.id} size={24}/></span><h3>{data.categories[c.id]}</h3><small>{MEASURES.filter(m=>m.category===c.id).length} {office.initiatives}</small><b>{allocation.find(x=>x.id===c.id).cost}<em>{t('units')}</em></b><ArrowUpRight size={17}/></Link>)}</div></section>}
 <section className="desk-panel register"><div className="desk-section-head"><h2>{office.decisionRegistry}</h2><Link to="/simulator">{office.openPlan}<ArrowUpRight size={16}/></Link></div>{decisions.length?<div className="register-list">{decisions.map((d,i)=>{const m=MEASURES.find(m=>m.id===d.measureId);return <Link key={d.measureId} to={`/simulator?district=${d.districtId||selected}`}><span>{i+1}</span><CategoryIcon id={m.category}/><div><b>{data.measures[m.id].name}</b><small>{d.districtId?data.districts[d.districtId].name:t('whole')}</small></div><strong>{m.cost}<small>{t('units')}</small></strong><ArrowUpRight size={16}/></Link>})}</div>:<div className="register-empty"><ListChecks size={30}/><div><h3>{office.noDecisions}</h3><p>{office.noDecisionsHint}</p></div><button className="btn secondary" disabled={!canEdit} onClick={()=>setDecisions(structuredClone(EXAMPLE))}>{office.startExample}<ArrowRight size={16}/></button></div>}</section><p className="desk-data-note">{office.dataNote}</p></div>;
}
