import React from 'react';
import {Link} from 'react-router-dom';
import {ArrowRight,ArrowUpRight,Compass,ShieldCheck,MoveUpRight} from 'lucide-react';
import {useApp} from './context.jsx';
import {CityMap} from './CityMap.jsx';
import {BASELINE} from '../../shared/engine.mjs';
export default function Home(){const {t,copy,data,number,decisions}=useApp();return <>
 <section className="home-hero"><div className="hero-copy"><span className="hero-label"><span className="pill-mark"/> Astana Innovations · 2026</span><h1>{copy.home.title}</h1><p>{copy.home.description}</p><div className="hero-actions"><Link className="btn primary large" to="/simulator">{decisions.length?t('continue'):copy.home.primary}<ArrowRight size={19}/></Link><Link className="text-link" to="/map">{copy.home.secondary}<ArrowUpRight size={18}/></Link></div><div className="hero-proof"><ShieldCheck size={17}/><span>{copy.methodology.description}</span></div></div><div className="hero-map"><CityMap districts={BASELINE.districts} compact/><div className="hero-map-caption"><span><Compass size={19}/>{copy.nav.map}</span><Link to="/map" className="round-button" aria-label={t('goMap')}><ArrowUpRight size={20}/></Link></div><div className="floating-score"><span>{t('baseline')}</span><strong>{number(BASELINE.score)}<small>/100</small></strong><div className="tiny-bars">{[45,62,68,72,48,55,78,60,75,70].map((v,i)=><i key={i} style={{height:v*.45}}/>)}</div></div></div></section>
 <section className="home-stats">{[[100,copy.home.budget],[5,copy.home.decisions],[5,copy.home.districts],[8,copy.home.horizon]].map(([v,l])=><div key={l}><b>{v}</b><span>{l}</span></div>)}</section>
 <section className="home-districts"><div className="section-title"><div><span className="eyebrow">{t('research')}</span><h2>{t('fairness')}</h2></div><Link className="text-link" to="/map">{t('goMap')}<ArrowRight size={18}/></Link></div><div className="district-cards">{BASELINE.districts.map((d,i)=><Link to={`/map?district=${d.id}`} className={`district-card district-${i}`} key={d.id}><div><span>{String(i+1).padStart(2,'0')}</span><ArrowUpRight size={19}/></div><h3>{data.districts[d.id].name}</h3><p>{data.districts[d.id].profile}</p><div className="district-card-score"><b>{number(d.score)}</b><span>{t('score')}</span></div></Link>)}</div></section>
 <section className="principle-strip"><div className="principle-number">70<span>/</span>30</div><div><h2>{copy.home.insightTitle}</h2><p>{t('fairnessText')}</p></div><Link className="btn secondary" to="/methodology">{t('readMore')}<ArrowUpRight size={17}/></Link></section>
 </>;}
