import React,{useState,lazy,Suspense} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {ArrowRight,MapPin} from 'lucide-react';
import {useApp} from './context.jsx';
import {PageHead,MetricGrid,Notice} from './components.jsx';
const CityScene=lazy(()=>import('./CityScene.jsx'));
import {BASELINE,calculate} from '../../shared/engine.mjs';
export default function MapPage(){const {t,copy,data,number,decisions,selectedDistrict,setSelectedDistrict}=useApp(),[params]=useSearchParams();const [selected,setSelected]=useState(BASELINE.districts.some(d=>d.id===params.get('district'))?params.get('district'):selectedDistrict),[after,setAfter]=useState(false);const result=after?calculate(decisions):BASELINE,d=result.districts.find(x=>x.id===selected);return <><PageHead eyebrow="Astana / 3D" title={copy.map.title} description={copy.map.description} actions={<div className="segmented">{[false,true].map(v=><button key={String(v)} aria-pressed={after===v} onClick={()=>setAfter(v)}>{v?t('after'):t('before')}</button>)}</div>}/><div className="explore-layout"><div className="explore-map"><Suspense fallback={<div className="loading">{t('loading')}</div>}><CityScene districts={result.districts} selected={selected} onSelect={id=>{setSelected(id);setSelectedDistrict(id);}}/></Suspense><div className="district-tabs">{result.districts.map(x=><button className={x.id===selected?'active':''} onClick={()=>{setSelected(x.id);setSelectedDistrict(x.id);}} key={x.id}>{data.districts[x.id].name}<b>{number(x.score)}</b></button>)}</div></div><aside className="district-panel"><div className="eyebrow"><MapPin size={15}/>{t('district')}</div><div className="district-panel-title"><h2>{data.districts[d.id].name}</h2><strong>{number(d.score)}<small>/100</small></strong></div><p>{data.districts[d.id].profile}</p><span className="population">{t('population')}: {Math.round(d.population*100)}%</span><MetricGrid district={d}/><Link className="btn primary full" to={`/district/${d.id}`}>{t('invest')}<ArrowRight size={18}/></Link></aside></div><Notice>{t('mapNotice')}</Notice></>;}

