// Public simulation workspace copy. Roles describe views, not verified offices.
export const OFFICE_COPY = {
  kk: {
    workspace: 'Қаланы басқару кабинеті',
    chooseRole: 'Жұмыс рөлін таңдаңыз',
    roleNote: 'Оқу симуляциясындағы рөл. Қызметтік өкілеттікті растау талап етілмейді.',
    mayor: 'Әкім',
    mayorDescription: 'Қаланың басым мәселелерін анықтап, бюджет пен қорытынды нәтижені бағалаңыз.',
    manager: 'Қалалық басқарушы',
    managerDescription: 'Аудандар бойынша шараларды жоспарлап, олардың құны мен әсерін салыстырыңыз.',
    enterWorkspace: 'Кабинетті ашу',
    switchRole: 'Рөлді ауыстыру',
    dashboard: 'Қаланың жалпы жағдайы',
    priorities: 'Басым міндеттер',
    weakDistricts: 'Қолдауды қажет ететін аудандар',
    budget: 'Қала бюджеті',
    remainingBudget: 'Қалған қаражат',
    qualityScore: 'Өмір сапасының баллы',
    decisions: 'Басқарушылық шешімдер',
    exploreMap: 'Аудандарды картадан қарау',
    detailedPlan: 'Шараларды жоспарлау',
    implementation: 'Іске асыру мерзімдері',
    yourScenarios: 'Сақталған сценарийлер',
    browserSession: 'Анонимді браузер сессиясы',
    browserSessionNote: 'Сценарийлер осы браузер сессиясына тіркеледі. Сессия деректерін тазартсаңыз, оларға қолжетімділік жоғалуы мүмкін.',
    aiAnalyze: 'AI талдауын алу',
    aiDescription: 'AI есептелген нәтижені түсіндіріп, ықтимал тәуекелдер мен жақсарту жолдарын ұсынады. Тіркелу қажет емес.',
    before: 'Бастапқы жағдай',
    after: 'Шешімдерден кейін',
    map2D: '2D карта',
    map3D: '3D көрініс',
    mapHeight: 'Аудан көлемінің биіктігі өмір сапасының синтетикалық баллын көрсетеді. Ғимараттардың нақты биіктігі көрсетілмейді.',
    rotate: 'Картаны бұру',
    rotateHint: 'Бұру басқару элементтері арқылы көру бұрышын өзгертіңіз.',
    resetCamera: 'Бастапқы көрініске оралу',
    mapUnavailable: 'Карта жүктелмеді. Аудандар тізімі арқылы жұмысты жалғастырыңыз.',
    webglFallback: 'Бұл құрылғыда 3D көрініс қолжетімсіз. 2D карта ашылды.',
    tryAgain: 'Қайта жүктеу',
    dataNote: 'Оқу моделі синтетикалық көрсеткіштерге негізделген. Нәтижелер Астананың нақты ағымдағы жағдайын сипаттамайды.',
  },
  ru: {
    workspace: 'Кабинет управления городом',
    chooseRole: 'Выберите рабочую роль',
    roleNote: 'Роль в учебном симуляторе. Подтверждение служебных полномочий не требуется.',
    mayor: 'Аким',
    mayorDescription: 'Определяйте приоритеты города, оценивайте бюджет и итоговый результат.',
    manager: 'Городской управленец',
    managerDescription: 'Планируйте меры по районам, сравнивайте их стоимость и влияние.',
    enterWorkspace: 'Открыть кабинет',
    switchRole: 'Сменить роль',
    dashboard: 'Обзор состояния города',
    priorities: 'Приоритетные задачи',
    weakDistricts: 'Районы, требующие поддержки',
    budget: 'Городской бюджет',
    remainingBudget: 'Остаток средств',
    qualityScore: 'Оценка качества жизни',
    decisions: 'Управленческие решения',
    exploreMap: 'Посмотреть районы на карте',
    detailedPlan: 'Планирование мероприятий',
    implementation: 'Сроки реализации',
    yourScenarios: 'Сохранённые сценарии',
    browserSession: 'Анонимная сессия браузера',
    browserSessionNote: 'Сценарии привязаны к этой сессии браузера. Очистка данных сессии может привести к потере доступа к ним.',
    aiAnalyze: 'Получить AI-анализ',
    aiDescription: 'AI объясняет рассчитанный результат, выявляет возможные риски и предлагает улучшения. Регистрация не требуется.',
    before: 'Исходное состояние',
    after: 'После решений',
    map2D: 'Карта 2D',
    map3D: 'Вид 3D',
    mapHeight: 'Высота объёма района показывает синтетическую оценку качества жизни. Реальная высота зданий не отображается.',
    rotate: 'Повернуть карту',
    rotateHint: 'Меняйте угол обзора с помощью элементов управления поворотом.',
    resetCamera: 'Вернуть исходный вид',
    mapUnavailable: 'Карта не загрузилась. Продолжите работу со списком районов.',
    webglFallback: 'На этом устройстве вид 3D недоступен. Открыта карта 2D.',
    tryAgain: 'Загрузить повторно',
    dataNote: 'Учебная модель использует синтетические показатели. Результаты не описывают реальное текущее состояние Астаны.',
  },
  en: {
    workspace: 'City management workspace',
    chooseRole: 'Choose your working role',
    roleNote: 'A role in an educational simulation. No official credentials are required.',
    mayor: 'Mayor',
    mayorDescription: 'Set city priorities and assess the budget and overall outcome.',
    manager: 'City manager',
    managerDescription: 'Plan measures by district and compare their costs and effects.',
    enterWorkspace: 'Open workspace',
    switchRole: 'Switch role',
    dashboard: 'City overview',
    priorities: 'Priority issues',
    weakDistricts: 'Districts needing support',
    budget: 'City budget',
    remainingBudget: 'Remaining funds',
    qualityScore: 'Quality of life score',
    decisions: 'Policy decisions',
    exploreMap: 'Explore districts on the map',
    detailedPlan: 'Measure planning',
    implementation: 'Implementation timelines',
    yourScenarios: 'Saved scenarios',
    browserSession: 'Anonymous browser session',
    browserSessionNote: 'Scenarios are linked to this browser session. Clearing session data may remove your access to them.',
    aiAnalyze: 'Get AI analysis',
    aiDescription: 'AI explains the calculated result, identifies possible risks and suggests improvements. No registration is required.',
    before: 'Starting conditions',
    after: 'After decisions',
    map2D: '2D map',
    map3D: '3D view',
    mapHeight: 'Each district’s raised height represents its synthetic quality of life score. Actual building heights are not shown.',
    rotate: 'Rotate map',
    rotateHint: 'Use the rotation controls to change the viewing angle.',
    resetCamera: 'Reset view',
    mapUnavailable: 'The map could not load. Continue using the district list.',
    webglFallback: 'The 3D view is unavailable on this device. The 2D map is open.',
    tryAgain: 'Reload',
    dataNote: 'This educational model uses synthetic indicators. Results do not describe current real-world conditions in Astana.',
  },
};
Object.assign(OFFICE_COPY.kk,{currentRole:'Жұмыс кеңістігі',simulationMode:'Қалалық симулятор',fixedConditions:'Бірдей бюджет · бірдей деректер',aiReady:'AI кеңесші',focusDistrict:'Таңдалған ауданға жақындау',loadingCity:'Қала моделі жүктелуде…',mayorTitle:'Әкімнің жұмыс үстелі',managerTitle:'Қалалық жоспарлау орталығы',mayorSubtitle:'Қаладағы басым мәселелерді анықтап, ресурстарды аудандарға бөліңіз.',managerSubtitle:'Іс-шараларды таңдап, мерзімін, бюджетін және ауданға әсерін бағалаңыз.',period:'Жоспарлау көкжиегі',quarters:'8 тоқсан',draft:'Ағымдағы жоспар',starting:'Бастапқы бюджет',used:'Жұмсалды',noCritical:'Критикалық көрсеткіш жоқ',needsAttention:'Назар аудару қажет',indicators:'көрсеткіш',planned:'шешім қабылданды',viewResults:'Жоспарды талдау',addDecision:'Шешім қосу',districtProfile:'Аудан жағдайы',lowest:'Ең төмен көрсеткіштер',target:'Мақсат: 40-тан жоғары',allocation:'Бюджеттің бағыттар бойынша бөлінуі',districtRanking:'Аудандардың жағдайы',planningDirections:'Жоспарлау бағыттары',initiatives:'бастама',sessionActive:'Жұмыс сессиясы ашық',sessionShort:'Кірусіз сақтау және AI талдауы қолжетімді.',startExample:'Мысалды қолдану',noDecisions:'Жоспарға әлі шара қосылмады',noDecisionsHint:'Ауданды таңдап, алғашқы шараны жоспарлаңыз.',openPlan:'Жоспарды ашу',workspaceError:'Жұмыс кеңістігі ашылмады. Бетті қайта жүктеңіз.',provisional:'Алдын ала есеп',scoreNote:'30% ең әлсіз ауданға байланысты',districtUnit:'аудан',savedHint:'Сценарийлер осы браузерде қайта ашылады.',decisionRegistry:'Шешімдер тізімі'});
Object.assign(OFFICE_COPY.ru,{currentRole:'Рабочее пространство',simulationMode:'Городской симулятор',fixedConditions:'Единый бюджет · единые данные',aiReady:'AI-советник',focusDistrict:'Приблизить выбранный район',loadingCity:'Загружаем модель города…',mayorTitle:'Рабочий стол акима',managerTitle:'Центр городского планирования',mayorSubtitle:'Определяйте приоритетные проблемы и распределяйте ресурсы между районами.',managerSubtitle:'Выбирайте мероприятия, оценивайте сроки, бюджет и влияние на районы.',period:'Горизонт планирования',quarters:'8 кварталов',draft:'Текущий план',starting:'Начальный бюджет',used:'Использовано',noCritical:'Критических показателей нет',needsAttention:'Требуют внимания',indicators:'показателя',planned:'решений принято',viewResults:'Проанализировать план',addDecision:'Добавить решение',districtProfile:'Состояние района',lowest:'Самые низкие показатели',target:'Цель: выше 40',allocation:'Бюджет по направлениям',districtRanking:'Состояние районов',planningDirections:'Направления планирования',initiatives:'инициативы',sessionActive:'Рабочая сессия открыта',sessionShort:'Сохранение и AI-анализ доступны без входа.',startExample:'Применить пример',noDecisions:'В плане пока нет мероприятий',noDecisionsHint:'Выберите район и запланируйте первую меру.',openPlan:'Открыть план',workspaceError:'Не удалось открыть рабочее пространство. Обновите страницу.',provisional:'Предварительный расчёт',scoreNote:'30% зависят от слабейшего района',districtUnit:'районов',savedHint:'Сценарии можно открыть снова в этом браузере.',decisionRegistry:'Реестр решений'});
Object.assign(OFFICE_COPY.en,{currentRole:'Workspace',simulationMode:'City simulation',fixedConditions:'Same budget · same starting data',aiReady:'AI advisor',focusDistrict:'Focus selected district',loadingCity:'Loading city model…',mayorTitle:'Mayor’s desk',managerTitle:'City planning centre',mayorSubtitle:'Identify priority issues and direct resources to the districts that need them.',managerSubtitle:'Plan initiatives and assess their cost, timing and impact on each district.',period:'Planning horizon',quarters:'8 quarters',draft:'Current plan',starting:'Starting budget',used:'Used',noCritical:'No critical indicators',needsAttention:'Need attention',indicators:'indicators',planned:'decisions made',viewResults:'Analyze plan',addDecision:'Add decision',districtProfile:'District profile',lowest:'Lowest indicators',target:'Target: above 40',allocation:'Budget by policy area',districtRanking:'District conditions',planningDirections:'Planning areas',initiatives:'initiatives',sessionActive:'Workspace is ready',sessionShort:'Save scenarios and use AI without signing in.',startExample:'Use example',noDecisions:'No initiatives in your plan yet',noDecisionsHint:'Choose a district and plan your first measure.',openPlan:'Open plan',workspaceError:'Your workspace could not open. Reload the page.',provisional:'Preliminary forecast',scoreNote:'30% depends on the weakest district',districtUnit:'districts',savedHint:'Reopen your scenarios in this browser.',decisionRegistry:'Decision register'});
