import React,{useEffect,useState,useRef} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {Download,Printer,Sparkles,ArrowUpRight} from 'lucide-react';
import {useApp,api} from './context.jsx';
import {PageHead,Empty,ErrorBox} from './components.jsx';
import {FUTURES_COPY} from './futures-copy.mjs';
import {FUTURE_NOTES,QuarterActions} from './Future.jsx';
import {simulate,BASELINE,projection} from '../../shared/engine.mjs';
import {MEASURES} from '../../shared/data.mjs';
import {QuarterChart,DistrictChart} from './ForecastCharts.jsx';
import {WHATIF_COPY} from './whatif-copy.mjs';
import deckStyles from './deck.css?inline';
import './deck.css';
export default function Presentation(){
 const {decisions,locale,t,data,number,office,role}=useApp(),f=FUTURES_COPY[locale],n=FUTURE_NOTES[locale],w=WHATIF_COPY[locale],result=simulate(decisions),series=result.valid?projection(decisions):[],[params]=useSearchParams();
 const [quarter,setQuarter]=useState(Math.max(0,Math.min(7,Math.trunc(Number(params.get('quarter'))||0)))),[analysis,setAnalysis]=useState(null),[error,setError]=useState(null),[busy,setBusy]=useState(false),[downloading,setDownloading]=useState(false),revision=useRef(0),pages=useRef();
 const signature=JSON.stringify(decisions);
 useEffect(()=>{const id=++revision.current;setAnalysis(null);setError(null);if(result.valid){setBusy(true);api('/api/analyze',{method:'POST',body:{decisions,locale}}).then(r=>{if(id===revision.current)setAnalysis(r);}).catch(e=>{if(id===revision.current)setError(e);}).finally(()=>{if(id===revision.current)setBusy(false);});}return()=>{revision.current++;};},[signature,locale]);
 async function download(){setDownloading(true);setError(null);try{const response=await fetch('/images/astana-concept.jpg');if(!response.ok)throw Error('loadError');const blob=await response.blob(),encoded=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob);});const content=pages.current.outerHTML.replaceAll('/images/astana-concept.jpg',encoded);const html=`<!doctype html><html lang="${locale}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AKIM — ${f.generatedDeck}</title><style>${deckStyles}</style></head><body class="standalone-deck">${content}</body></html>`;const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`AKIM-${locale}-Q${quarter+1}.html`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e);}finally{setDownloading(false);}}
 if(!result.valid)return <><PageHead title={f.generatedDeck}/><Empty title={t('invalidCount')}><Link className="btn primary" to="/advisor?allocate=1"><Sparkles size={16}/>{f.AIallocation}</Link></Empty></>;
 const foot=<footer>{office.dataNote}</footer>,negative=result.districts.flatMap(d=>Object.entries(d.deltas).filter(([,v])=>v<0).map(([k,v])=>`${data.districts[d.id].name}: ${data.metrics[k]} ${number(v)}`));
 return <><PageHead eyebrow="CITY / BRIEFING" title={f.generatedDeck} description={f.explainAllocation} actions={<><button className="btn secondary" onClick={()=>window.print()}><Printer size={16}/>PDF / {t('print')}</button><button className="btn primary" disabled={downloading} onClick={download}><Download size={16}/>{f.downloadHtml}</button></>}/><div className="deck-controls"><label>{f.nextQuarter}<select value={quarter} onChange={e=>setQuarter(Number(e.target.value))}>{Array.from({length:8},(_,q)=><option value={q} key={q}>Q{q+1}</option>)}</select></label><span>6 {locale==='kk'?'слайд':locale==='ru'?'слайдов':'slides'} · {busy?t('analyzing'):analysis?.mode==='ai'?'AI':t('local')}</span><Link className="text-link" to="/vision">{f.beforeAfter}<ArrowUpRight size={16}/></Link></div>{error&&<ErrorBox error={error}/>}<div className="deck-pages" ref={pages}>
 <section className="deck-slide deck-cover"><div><p className="deck-kicker">AKIM / ASTANA CITY LAB</p><h1>{f.slides[0]}</h1><p>{office[role]}</p><div className="deck-headline">{number(result.score)}<small>Astana Quality of Life Score</small></div><p>{number(BASELINE.score)} → {number(result.score)} &nbsp; +{number(result.delta)}</p><p>{t('budget')}: {result.cost}/100</p></div><figure><img src="/images/astana-concept.jpg" alt={f.illustrationOnly}/><figcaption>{f.illustrationOnly}</figcaption></figure>{foot}</section>
 <section className="deck-slide"><h2>{f.slides[1]}</h2><table className="deck-table"><thead><tr><th>{t('name')}</th><th>{t('district')}</th><th>{t('budget')}</th><th>{n.firstEffect}</th></tr></thead><tbody>{decisions.map(d=>{const m=MEASURES.find(m=>m.id===d.measureId);return <tr key={m.id}><td><b>{m.id}</b> {data.measures[m.id].name}</td><td>{d.districtId?data.districts[d.districtId].name:t('whole')}</td><td>{m.cost}</td><td>Q{m.lag+1}</td></tr>;})}</tbody></table><p className="deck-emphasis">{n.allotment}: {result.cost}/100. {office.remainingBudget}: {result.remaining}.</p><p className="deck-note">{locale==='kk'?'Бюджет жоспар басында толық бөлінеді. Кесте нақты төлем кестесін сипаттамайды.':locale==='ru'?'Бюджет выделяется целиком в начале плана. Это не календарь фактических платежей.':'The full budget is committed at the start. This is not an actual cash-flow schedule.'}</p>{foot}</section>
 <section className="deck-slide"><h2>{f.slides[2]}</h2><div className="deck-two"><div><DistrictChart result={result}/></div><div><QuarterChart series={series}/><p className="deck-note">{n.trajectory}</p></div></div>{foot}</section>
 <section className="deck-slide"><h2>{f.slides[3]}</h2><p className="deck-note">{w.shapleyNote}</p><div className="deck-shapley">{result.shapley.map(c=><div key={c.measureId}><span>{c.measureId} {data.measures[c.measureId].name}</span><div><i style={{width:Math.abs(c.value)/Math.max(...result.shapley.map(x=>Math.abs(x.value)),.001)*100+'%'}}/></div><b>{c.value>=0?'+':''}{number(c.value)}</b></div>)}</div><p className="deck-emphasis">Σ = +{number(result.delta)} Score</p>{foot}</section>
 <section className="deck-slide"><h2>{f.slides[4]}</h2><div className="deck-two"><div><h3>{locale==='kk'?'Күтілетін нәтиже':locale==='ru'?'Ожидаемый результат':'Expected outcomes'}</h3><ul>{(analysis?.report.strengths||[`${t('budget')}: ${result.cost}/100`,`${t('critical')}: ${result.critical.length}`]).slice(0,3).map((x,i)=><li key={i}>{x}</li>)}</ul></div><div><h3>{t('weakest')}: {data.districts[result.weakest.id].name}</h3><ul>{(analysis?.report.risks||[`${t('critical')}: ${result.critical.length}`,n.trajectory]).slice(0,3).map((x,i)=><li key={i}>{x}</li>)}</ul>{negative.length>0&&<p className="deck-note">{negative.slice(0,2).join('. ')}</p>}</div></div><p className="deck-note">{analysis?.mode==='ai'?'AI':t('local')} · {office.dataNote}</p>{foot}</section>
 <section className="deck-slide"><h2>Q{quarter+1}. {f.slides[5]}</h2><QuarterActions quarter={quarter}/><p className="deck-note">{n.trajectory}</p>{foot}</section>
 </div></>;
}
