import React,{useEffect,useState,useRef,lazy,Suspense} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {Download,Printer,Sparkles} from 'lucide-react';
import {useApp,api} from './context.jsx';
import {PageHead,ErrorBox,Notice} from './components.jsx';
import {districtFacts,districtIdOrDefault} from '../../shared/district.mjs';
import {nextQuarterFacts} from '../../shared/planning.mjs';
import {QuarterChart} from './ForecastCharts.jsx';
import {QUARTER_TASKS} from './quarter-tasks.mjs';
import {FUTURE_NOTES} from './Future.jsx';
import deckStyles from './deck.css?inline';
import './deck.css';
const StreetScene=lazy(()=>import('./StreetScene.jsx'));
const COPY={
 kk:{index:'Аудан индексі',title:'Ауданда не өзгереді',projects:'Ауданға әсер ететін шешімдер',metrics:'Көрсеткіштердің өзгерісі',timeline:'Өзгеріс қашан басталады',risks:'Нәтиже және тәуекелдер',next:'Келесі тоқсанның жоспары',local:'Осы ауданға тікелей бөлінген',city:'Жалпықалалық шаралардың толық құны',total:'Қала жоспарының жалпы бюджеті',shared:'Жалпықалалық шығын ауданға жеке қайта есептелмейді.',first:'Алғашқы әсер',change:'Өзгеріс',noMeasures:'Бұл ауданға әсер ететін шара жоқ.',noChanges:'Көрсеткіштер өзгермейді.',download:'HTML жүктеу',print:'PDF / Басып шығару',draft:'Алдын ала аудандық есеп. Ресми қала Score үшін бес шешім керек.',noCritical:'40-тан төмен көрсеткіштер',explain:'Аудан бойынша AI түсіндірмесі',chart:'Шкала: 0–100, жоғары болғаны жақсы',ready:'Көріністер дайындалуда…'},
 ru:{index:'Индекс района',title:'Что изменится в районе',projects:'Решения, влияющие на район',metrics:'Изменения показателей',timeline:'Когда начнутся изменения',risks:'Результат и риски',next:'План следующего квартала',local:'Прямые вложения в этот район',city:'Полная стоимость общегородских мер',total:'Общий бюджет городского плана',shared:'Общегородские расходы не считаются отдельным бюджетом каждого района.',first:'Первый эффект',change:'Изменение',noMeasures:'Мер, влияющих на этот район, нет.',noChanges:'Показатели не меняются.',download:'Скачать HTML',print:'PDF / Печать',draft:'Предварительный районный отчёт. Для официального городского Score нужны пять решений.',noCritical:'Показатели ниже 40',explain:'AI-объяснение по району',chart:'Шкала: 0–100, больше — лучше',ready:'Подготовка изображений…'},
 en:{index:'District index',title:'What changes in the district',projects:'Decisions affecting this district',metrics:'Indicator changes',timeline:'When changes begin',risks:'Outcomes and risks',next:'Next quarter’s plan',local:'Direct investment in this district',city:'Full cost of citywide measures',total:'Total city plan budget',shared:'Citywide spending is not counted as a separate budget for each district.',first:'First effect',change:'Change',noMeasures:'No selected measures affect this district.',noChanges:'Indicators remain unchanged.',download:'Download HTML',print:'PDF / Print',draft:'Provisional district report. Five decisions are required for the official city Score.',noCritical:'Indicators below 40',explain:'District AI explanation',chart:'Scale: 0–100, higher is better',ready:'Preparing scene images…'}
};
export default function Presentation({districtId:propId,embedded=false}){
 const {decisions,locale,t,data,number,v4,selectedDistrict,canEdit}=useApp(),[params]=useSearchParams(),districtId=districtIdOrDefault(propId||params.get('district')||selectedDistrict),c=COPY[locale],f=districtFacts(decisions,districtId),name=data.districts[districtId].name;
 const [quarter,setQuarter]=useState(Math.max(0,Math.min(7,Math.trunc(Number(params.get('quarter'))||0)))),[analysis,setAnalysis]=useState(null),[error,setError]=useState(null),[busy,setBusy]=useState(false),[downloading,setDownloading]=useState(false),[shots,setShots]=useState({}),revision=useRef(0),pages=useRef();
 const signature=JSON.stringify(decisions),shotKey=districtId+signature,notes=FUTURE_NOTES[locale];
 const capture=(q,image)=>setShots(old=>({...old,[shotKey+q]:image||'fallback'})),beforeShot=shots[shotKey+0],afterShot=shots[shotKey+8],snapshotsReady=!!beforeShot&&!!afterShot;
 useEffect(()=>{revision.current++;setAnalysis(null);setError(null);setBusy(false);return()=>{revision.current++;};},[signature,locale,districtId,canEdit]);
 async function analyze(){const stamp=++revision.current;setBusy(true);setError(null);try{const r=await api('/api/analyze',{method:'POST',body:{decisions,locale,districtId}});if(stamp===revision.current)setAnalysis(r);}catch(e){if(stamp===revision.current)setError(e);}finally{if(stamp===revision.current)setBusy(false);}}
 async function download(){setDownloading(true);setError(null);try{let content=pages.current.outerHTML;if(content.includes('/images/astana-concept.jpg')){const response=await fetch('/images/astana-concept.jpg');if(!response.ok)throw Error('loadError');const blob=await response.blob(),encoded=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(blob);});content=content.replaceAll('/images/astana-concept.jpg',encoded);}const html='<!doctype html><html lang="'+locale+'"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AKIM — '+name+'</title><style>'+deckStyles+'</style></head><body class="standalone-deck">'+content+'</body></html>';const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='AKIM-'+districtId+'-'+locale+'-Q'+(quarter+1)+'.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e);}finally{setDownloading(false);}}
 const foot=<footer>{name} · {v4.district.sceneNote}</footer>,next=nextQuarterFacts(decisions,quarter).measures.filter(m=>!m.districtId||m.districtId===districtId);
 const renderShot=q=>{const shot=shots[shotKey+q];return <figure className="district-deck-shot">{shot?<img src={shot==='fallback'?'/images/astana-concept.jpg':shot} alt={name+' · '+(q===0?t('before'):t('after'))}/>:<Suspense fallback={<div>{c.ready}</div>}><StreetScene key={shotKey+q} districtId={districtId} decisions={decisions} quarter={q} playing={false} trafficChange={q?f.after.metrics.T1-f.before.metrics.T1:0} label={name} onSnapshot={image=>capture(q,image)}/></Suspense>}<figcaption>{q===0?t('before'):t('after')} · Q{q}</figcaption></figure>;};
 return <><PageHead title={v4.district.reportTitle+' · '+name} description={v4.district.reportSubtitle} actions={<><button className="btn secondary" disabled={!snapshotsReady} onClick={()=>window.print()}><Printer size={16}/>{c.print}</button><button className="btn primary" disabled={downloading||!snapshotsReady} onClick={download}><Download size={16}/>{snapshotsReady?c.download:c.ready}</button></>}/><div className="deck-controls"><label>{c.next}<select value={quarter} onChange={e=>setQuarter(Number(e.target.value))}>{Array.from({length:8},(_,q)=><option value={q} key={q}>Q{q+1}</option>)}</select></label><span>6 {locale==='kk'?'слайд':locale==='ru'?'слайдов':'slides'}</span>{canEdit&&<button className="btn secondary" disabled={busy} onClick={analyze}><Sparkles size={16}/>{busy?t('analyzing'):c.explain}</button>}</div>{decisions.length!==5&&<Notice>{c.draft}</Notice>}{error&&<ErrorBox error={error}/>}<div className="deck-pages district-deck" ref={pages}>
 <section className="deck-slide district-deck-cover"><p className="deck-kicker">AKIM / {name}</p><h1>{c.title}: {name}</h1><div className="district-deck-headline"><span>{c.index}</span><b>{number(f.before.score)} → {number(f.after.score)}</b><small>{c.change}: {f.delta>0?'+':''}{number(f.delta)}</small></div><div className="district-deck-pair">{renderShot(0)}{renderShot(8)}</div>{foot}</section>
 <section className="deck-slide"><h2>{c.projects}</h2>{f.measures.length?<table className="deck-table"><thead><tr><th>{t('decisions')}</th><th>{t('district')}</th><th>{t('budget')}</th><th>{c.first}</th></tr></thead><tbody>{f.measures.map(m=><tr key={m.id}><td><b>{m.id}</b> {data.measures[m.id].name}</td><td>{m.scope==='city'?t('whole'):name}</td><td>{m.cost}</td><td>Q{m.lag+1}</td></tr>)}</tbody></table>:<p>{c.noMeasures}</p>}<div className="district-deck-costs"><p>{c.local}<b>{f.localCost}</b></p><p>{c.city}<b>{f.citywideCost}</b></p><p>{c.total}<b>{f.city.cost}/100</b></p></div><p className="deck-note">{c.shared}</p>{foot}</section>
 <section className="deck-slide"><h2>{c.metrics} · {name}</h2><p className="deck-note">{c.chart}</p><div className="district-deck-metrics">{f.metrics.map(m=><div key={m.key}><span>{data.metrics[m.key]}</span><b>{number(m.before)} → {number(m.after)}</b><div><i style={{width:m.before+'%'}}/><i style={{width:m.after+'%'}}/></div></div>)}</div>{foot}</section>
 <section className="deck-slide"><h2>{c.timeline} · {name}</h2><QuarterChart series={f.series} title={c.index}/><p className="deck-note">{notes.trajectory}</p><p className="deck-emphasis">{c.noCritical}: {f.criticalBefore} → {f.criticalAfter}</p>{foot}</section>
 <section className="deck-slide"><h2>{c.risks} · {name}</h2><div className="deck-two-columns"><div><h3>{v4.district.impactTitle}</h3><ul>{(analysis?.report.strengths?.length?analysis.report.strengths:f.metrics.filter(m=>m.delta>0).sort((a,b)=>b.delta-a.delta).slice(0,3).map(m=>data.metrics[m.key]+': '+number(m.before)+' → '+number(m.after))).map((text,i)=><li key={i}>{text}</li>)}</ul>{f.delta===0&&<p>{c.noChanges}</p>}</div><div><h3>{{kk:'Тәуекелдер',ru:'Риски',en:'Risks'}[locale]}</h3><ul>{(analysis?.report.risks?.length?analysis.report.risks:[c.noCritical+': '+f.criticalAfter,...f.metrics.filter(m=>m.delta<0).map(m=>data.metrics[m.key]+': '+number(m.before)+' → '+number(m.after)),notes.trajectory]).slice(0,3).map((text,i)=><li key={i}>{text}</li>)}</ul></div></div><p className="deck-note">{analysis?.mode==='ai'?'AI · ':''}{name} · {c.index}: {number(f.after.score)}</p>{foot}</section>
 <section className="deck-slide"><h2>Q{quarter+1}. {name}: {c.next}</h2>{next.length?<div className="quarter-actions">{next.map(m=><article key={m.measureId}><span>{m.measureId}</span><div><h3>{data.measures[m.measureId].name}</h3><p>{m.stage==='waiting'?QUARTER_TASKS[locale][m.measureId]:notes[m.stage]}</p><small>{c.first}: Q{m.firstEffectQuarter}</small></div></article>)}</div>:<p>{c.noMeasures}</p>}<p className="deck-note">{notes.trajectory}</p>{foot}</section>
 </div>{!embedded&&<Link className="btn secondary" to={'/district/'+districtId}>{v4.district.workspace}</Link>}</>;
}

