// Preparation suggestions for the next simulated quarter; no measured claims.
export const QUARTER_TASKS = {
  kk: {
    M1: 'Автобус жолағына арналған көшені таңдап, аялдамалар мен қозғалыс сызбасын нақтылаңыз.',
    M2: 'Бағдаршамдарды баптау үшін қиылыстардағы көлік ағыны мен сигнал кезеңдері туралы деректерді жинаңыз.',
    M3: 'ЛРТ бағытын, құрылыс кезеңдерін және құрылыс кезіндегі айналма жолдарды нақтылаңыз.',
    M4: 'Саябақ учаскесін таңдап, жердің қолжетімділігі мен инженерлік желілерді тексеріңіз.',
    M5: 'Жеке үйлердің отынға қажеттілігін, жеткізу мүмкіндігін және ауысу шығындарын бағалаңыз.',
    M6: 'Басым жел бағытын ескеріп, жасыл белдеу орындары мен ағаш түрлерін таңдаңыз.',
    M7: 'Мектеп пен балабақша учаскесін анықтап, балалардың қауіпсіз жету жолдарын тексеріңіз.',
    M8: 'Емхананың қызмет көрсету аумағын анықтап, тұрғындардың оған жету қолайлылығын тексеріңіз.',
    M9: 'Спорт алаңдарына арналған аулаларды таңдап, тұрғындардың қажеттілігі мен кедергісіз қолжетімділікті бағалаңыз.',
    M10: 'Жарықтандырудағы олқылықтар мен камералар қамтымайтын аумақтарды белгілеп, орнату орындарын таңдаңыз.',
    M11: 'Балалардың мектепке баратын бағыттарын картаға түсіріп, қауіпсіз өткелдердің орнын анықтаңыз.',
    M12: 'Өтініш түрлерін, жауапты қызметтерді және орындалу мәртебелерін анықтаңыз.',
    M13: 'Жылу және су желілерінің жағдайын тексеріп, жаңартылатын учаскелер мен жұмыс кезегін анықтаңыз.',
    M14: 'Апаттық бригадалардың кезекшілік кестесін жасап, тұрғындарды хабардар ету арналарын тексеріңіз.',
  },
  ru: {
    M1: 'Выберите улицу для автобусной полосы и уточните расположение остановок и схему движения.',
    M2: 'Соберите данные о потоках на перекрёстках и фазах сигналов для настройки светофоров.',
    M3: 'Уточните маршрут ЛРТ, этапы строительства и временные объезды.',
    M4: 'Выберите участок для парка и проверьте доступность земли и расположение инженерных сетей.',
    M5: 'Оцените потребности частных домов в топливе, возможности поставок и затраты перехода.',
    M6: 'Определите места зелёных полос и подходящие породы деревьев с учётом преобладающих ветров.',
    M7: 'Определите участок для школы и детсада и проверьте безопасные пути доступа детей.',
    M8: 'Определите зону обслуживания поликлиники и проверьте удобство доступа жителей.',
    M9: 'Выберите дворы для спортплощадок и оцените потребности жителей и безбарьерный доступ.',
    M10: 'Отметьте пробелы в освещении и охвате камерами, затем выберите места установки.',
    M11: 'Нанесите школьные пешеходные маршруты на карту и определите места безопасных переходов.',
    M12: 'Определите категории обращений, ответственные службы и статусы исполнения.',
    M13: 'Проверьте состояние тепло- и водосетей, определите участки обновления и очерёдность работ.',
    M14: 'Составьте график дежурств аварийных бригад и проверьте каналы оповещения жителей.',
  },
  en: {
    M1: 'Choose a street for the bus lane and confirm stop locations and traffic arrangements.',
    M2: 'Collect junction traffic flows and signal phase data to configure adaptive traffic lights.',
    M3: 'Confirm the light rail route, construction stages and temporary diversions.',
    M4: 'Select a park site and check land availability and utility locations.',
    M5: 'Assess household fuel needs, supply options and transition costs.',
    M6: 'Choose green belt locations and suitable tree species based on prevailing winds.',
    M7: 'Identify the school and kindergarten site and check safe access routes for children.',
    M8: 'Define the clinic’s service area and check how easily residents can reach it.',
    M9: 'Select courtyards for sports facilities and assess resident needs and accessible entry.',
    M10: 'Identify lighting and camera coverage gaps, then select installation locations.',
    M11: 'Map walking routes to schools and identify locations for safer crossings.',
    M12: 'Define request categories, responsible services and resolution statuses.',
    M13: 'Inspect heating and water networks, then prioritise upgrade sections and construction stages.',
    M14: 'Prepare emergency crew rotas and check channels for alerting residents.',
  },
};
