import React,{useEffect,useState,useRef} from 'react';
import {Link,useNavigate,useParams,useSearchParams} from 'react-router-dom';
import {Plus,ArrowUpRight,Trash2,Share2,Trophy,GitCompareArrows,Pencil,Check} from 'lucide-react';
import {useApp,api} from './context.jsx';
import {PageHead,Loading,ErrorBox,Empty,WorkspaceStatus,Modal,Notice} from './components.jsx';
import {Results} from './Results.jsx';
import {DISTRICTS,METRICS} from '../../shared/data.mjs';
function useResource(path){const [value,setValue]=useState(null),[error,setError]=useState(null),[tick,setTick]=useState(0);useEffect(()=>{let active=true;setValue(null);setError(null);api(path).then(r=>{if(active)setValue(r);}).catch(e=>{if(active)setError(e);});return()=>{active=false};},[path,tick]);return {value,setValue,error,reload:()=>setTick(x=>x+1)};}
export function Scenarios(){const {t,copy,config,number,locale}=useApp(),{value,error,reload}=useResource('/api/scenarios');const [selected,setSelected]=useState([]),[removing,setRemoving]=useState(null),[busy,setBusy]=useState(false),[actionError,setActionError]=useState(null);async function remove(){setBusy(true);try{await api(`/api/scenarios/${removing.id}`,{method:'DELETE'});setSelected(s=>s.filter(id=>id!==removing.id));setRemoving(null);reload();}catch(e){setActionError(e);}finally{setBusy(false);}}
 return <><PageHead eyebrow="City Lab / 04" title={copy.scenarios.title} description={copy.scenarios.description} actions={<Link className="btn primary" to="/simulator"><Plus size={18}/>{t('start')}</Link>}/>{config&&!config.user?<WorkspaceStatus/>:error?<ErrorBox error={error} retry={reload}/>:!value?<Loading/>:!value.scenarios.length?<Empty title={t('empty')} text={t('emptyHint')}><Link className="btn primary" to="/simulator">{t('start')}<ArrowUpRight size={18}/></Link></Empty>:<><div className="list-toolbar"><span>{t('comparePick')} · {selected.length}/3</span><Link aria-disabled={selected.length<2} className={`btn secondary ${selected.length<2?'disabled':''}`} to={`/compare?ids=${selected.join(',')}`}><GitCompareArrows size={17}/>{t('compare')}</Link></div><div className="scenario-grid">{value.scenarios.map(s=><article className="scenario-card" key={s.id}><div className="scenario-card-top"><label className="compare-checkbox"><input type="checkbox" aria-label={`${t('compare')}: ${s.name}`} checked={selected.includes(s.id)} disabled={!selected.includes(s.id)&&selected.length>=3} onChange={e=>setSelected(ids=>e.target.checked?[...ids,s.id]:ids.filter(x=>x!==s.id))}/>{t('compare')}</label>{s.published&&<span className="small-badge"><Trophy size={13}/>{t('published')}</span>}</div><h2><Link to={`/scenarios/${s.id}`}>{s.name}</Link></h2><p>{s.team}</p><div className="scenario-score"><strong>{number(s.result.score)}</strong><span>Astana Quality of Life Score</span></div><div className="scenario-meta"><span>{t('budget')} <b>{s.result.cost}/100</b></span><span>{new Date(s.createdAt).toLocaleDateString(locale)}</span></div><div className="scenario-card-actions"><Link className="btn secondary" to={`/scenarios/${s.id}`}>{t('open')}<ArrowUpRight size={16}/></Link><button className="icon-button" aria-label={`${t('delete')}: ${s.name}`} onClick={()=>{setActionError(null);setRemoving(s)}}><Trash2 size={18}/></button></div></article>)}</div></>}{removing&&<Modal title={t('deleteConfirm')} onClose={()=>setRemoving(null)}><p>{removing.name}</p>{actionError&&<ErrorBox error={actionError}/>}<div className="modal-actions"><button className="btn secondary" onClick={()=>setRemoving(null)}>{t('cancel')}</button><button className="btn danger-btn" disabled={busy} onClick={remove}>{t('delete')}</button></div></Modal>}</>;
}
export function ScenarioDetail({shared=false}){const {id}=useParams(),navigate=useNavigate(),{t,data,locale,setDecisions,notify,canEdit}=useApp(),{value,setValue,error,reload}=useResource(shared?`/api/shared/${id}`:`/api/scenarios/${id}`);const [analysis,setAnalysis]=useState(null),[busy,setBusy]=useState(false),[actionError,setActionError]=useState(null),[link,setLink]=useState(''),[publishing,setPublishing]=useState(false),[mutating,setMutating]=useState(false),revision=useRef(0);useEffect(()=>{revision.current++;setAnalysis(null);setBusy(false);setLink('');return()=>{revision.current++;};},[id,locale]);const s=value?.scenario;
 async function analyze(){const stamp=++revision.current;setBusy(true);setActionError(null);try{const response=await api('/api/analyze',{method:'POST',body:{decisions:s.decisions,locale}});if(stamp===revision.current)setAnalysis(response);}catch(e){if(stamp===revision.current)setActionError(e);}finally{if(stamp===revision.current)setBusy(false);}}
 async function mutate(kind){setMutating(true);setActionError(null);try{const r=await api(`/api/scenarios/${s.id}/${kind}`,{method:'POST',body:{}});setValue(r);if(kind==='share'){const url=`${location.origin}/share/${r.scenario.shareId}`;setLink(url);try{await navigator.clipboard.writeText(url);notify(t('copied'));}catch{}}setPublishing(false);}catch(e){setActionError(e);}finally{setMutating(false);}}
 function edit(decisions){if(setDecisions(decisions))navigate('/simulator');}
 if(error)return <><PageHead title={t('notFound')}/><ErrorBox error={error} retry={reload}/><Link className="btn secondary" to="/scenarios">{t('back')}</Link></>;if(!s)return <Loading/>;
 return <><PageHead eyebrow={shared?t('shared'):t('myScenarios')} title={s.name} description={s.team} actions={<>{canEdit&&<button className="btn secondary" onClick={()=>edit(s.decisions)}><Pencil size={16}/>{t('edit')}</button>}{!shared&&canEdit&&<><button className="btn secondary" disabled={mutating} onClick={()=>mutate('share')}><Share2 size={16}/>{t('share')}</button><button className="btn primary" disabled={s.published||mutating} onClick={()=>setPublishing(true)}><Trophy size={16}/>{s.published?t('published'):t('publish')}</button></>}</>}/>{shared&&<Notice>{t('sharedRead')}</Notice>}{link&&<div className="share-output"><label>{t('share')}<input readOnly value={link} onFocus={e=>e.target.select()}/></label></div>}{actionError&&<ErrorBox error={actionError}/>}<div className="decision-chips">{s.decisions.map(d=><span key={d.measureId}><Check size={14}/>{data.measures[d.measureId].name}<small>{d.districtId?data.districts[d.districtId].name:t('whole')}</small></span>)}</div><Results result={s.result} decisions={s.decisions} analysis={analysis} busy={busy} onAnalyze={analyze} onApply={edit} allowSave={shared}/>{publishing&&<Modal title={t('publish')} onClose={()=>setPublishing(false)}><p>{t('publishNote')}</p><p><b>{s.team} · {s.name}</b></p><div className="modal-actions"><button className="btn secondary" onClick={()=>setPublishing(false)}>{t('cancel')}</button><button className="btn primary" disabled={mutating} onClick={()=>mutate('publish')}>{t('publish')}</button></div></Modal>}</>;
}
export function Leaderboard(){const {t,copy,number}=useApp(),{value,error,reload}=useResource('/api/leaderboard');return <><PageHead eyebrow="City Lab / 05" title={copy.leaderboard.title} description={t('leaderNote')} actions={<Link className="btn primary" to="/scenarios">{t('myScenarios')}<ArrowUpRight size={17}/></Link>}/>{error?<ErrorBox error={error} retry={reload}/>:!value?<Loading/>:!value.scenarios.length?<Empty title={t('leaderEmpty')} text={t('publishNote')}><Link className="btn primary" to="/simulator">{t('start')}</Link></Empty>:<div className="surface table-scroll leaderboard"><table><thead><tr><th>#</th><th>{t('team')}</th><th>{t('name')}</th><th>{t('budget')}</th><th>QoL Score</th><th/></tr></thead><tbody>{value.scenarios.map((s,i)=><tr key={s.id}><td><span className={`rank rank-${i+1}`}>{i+1}</span></td><td><b>{s.team}</b></td><td>{s.name}</td><td>{s.result.cost}/100</td><td className="table-score">{number(s.result.score)}</td><td><Link className="text-link" to={`/share/${s.shareId}`}>{t('open')}<ArrowUpRight size={17}/></Link></td></tr>)}</tbody></table></div>}<Notice>{copy.methodology.dataNote}</Notice></>;}
export function Compare(){const {t,data,number}=useApp(),[params]=useSearchParams(),{value,error,reload}=useResource('/api/scenarios'),ids=(params.get('ids')||'').split(',').slice(0,3);const scenarios=value?.scenarios.filter(s=>ids.includes(s.id))||[];return <><PageHead eyebrow="City Lab" title={t('compareTitle')} actions={<Link className="btn secondary" to="/scenarios">{t('back')}</Link>}/>{error?<ErrorBox error={error} retry={reload}/>:!value?<Loading/>:scenarios.length<2?<Empty title={t('comparePick')}><Link className="btn primary" to="/scenarios">{t('myScenarios')}</Link></Empty>:<><div className="surface table-scroll comparison"><table><thead><tr><th>{t('indicator')}</th>{scenarios.map(s=><th key={s.id}><Link to={`/scenarios/${s.id}`}>{s.name}<ArrowUpRight size={15}/></Link><small>{s.team}</small></th>)}</tr></thead><tbody><tr className="comparison-total"><td>Astana Quality of Life Score</td>{scenarios.map(s=><td key={s.id}>{number(s.result.score)}</td>)}</tr><tr><td>{t('budget')}</td>{scenarios.map(s=><td key={s.id}>{s.result.cost}/100</td>)}</tr><tr><td>{t('critical')}</td>{scenarios.map(s=><td key={s.id}>{s.result.critical.length}</td>)}</tr>{DISTRICTS.map(d=><tr key={d.id}><td>{data.districts[d.id].name}</td>{scenarios.map(s=><td key={s.id}>{number(s.result.districts.find(x=>x.id===d.id).score)}</td>)}</tr>)}</tbody></table></div><div className="compare-decisions">{scenarios.map(s=><section className="surface" key={s.id}><h2>{s.name}</h2><ol>{s.decisions.map(d=><li key={d.measureId}>{data.measures[d.measureId].name}<small>{d.districtId?data.districts[d.districtId].name:t('whole')}</small></li>)}</ol></section>)}</div></>}</>;}

