import React,{useEffect,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {ArrowRight,ArrowLeft,RotateCcw,Plus,Check,Trash2,Clock3,MapPin,Sparkles} from 'lucide-react';
import {useApp,api} from './context.jsx';
import {PageHead,CategoryIcon,COLORS,ErrorBox,Notice} from './components.jsx';
import {CATEGORIES,DISTRICTS,MEASURES,EXAMPLE} from '../../shared/data.mjs';
import {BASELINE,calculate,validate} from '../../shared/engine.mjs';
import {Results} from './Results.jsx';
export default function Simulator(){
 const {t,copy,data,number,locale,decisions,setDecisions,errorText}=useApp(),[params]=useSearchParams();
 const [district,setDistrict]=useState(DISTRICTS.some(d=>d.id===params.get('district'))?params.get('district'):'nura'),[filter,setFilter]=useState('all'),[stage,setStage]=useState(2),[analysis,setAnalysis]=useState(null),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(null);const revision=useRef(0);
 useEffect(()=>{revision.current++;setAnalysis(null);setResult(null);setStage(2);setBusy(false);},[JSON.stringify(decisions)]);
 useEffect(()=>{revision.current++;setAnalysis(null);setBusy(false);},[locale]);
 const preview=calculate(decisions),check=validate(decisions);
 async function evaluate(){const id=++revision.current;setBusy(true);setError(null);try{const r=await api('/api/simulate',{method:'POST',body:{decisions}});if(id!==revision.current)return;setResult(r);setStage(3);window.scrollTo({top:0});const report=await api('/api/analyze',{method:'POST',body:{decisions,locale}});if(id===revision.current)setAnalysis(report);}catch(e){if(id===revision.current)setError(e);}finally{if(id===revision.current)setBusy(false);}}
 function add(m){const d=m.scope==='city'?{measureId:m.id}:{measureId:m.id,districtId:district};const next=[...decisions,d];if(validate(next,{partial:true}).valid)setDecisions(next);}
 return <><PageHead eyebrow={t('brand')} title={stage===3?t('resultTitle'):copy.simulation.title} description={stage===3?t('resultSub'):copy.simulation.description} actions={stage===2?<button className="btn secondary" onClick={()=>setDecisions(structuredClone(EXAMPLE))}>{t('demo')}<ArrowUpRightIcon/></button>:<button className="btn secondary" onClick={()=>setStage(2)}><ArrowLeft size={17}/>{copy.simulation.revise}</button>}/><div className="steps"><Link to="/map"><span>1</span>{t('step1')}</Link><button className={stage===2?'active':'done'} onClick={()=>setStage(2)}><span>{stage===3?<Check size={15}/>:2}</span>{t('step2')}</button><button className={stage===3?'active':''} disabled={!result} onClick={()=>result&&setStage(3)}><span>3</span>{t('step3')}</button></div>{error&&<ErrorBox error={error} retry={evaluate}/>}
 {stage===3&&result?<Results result={result} decisions={decisions} analysis={analysis} busy={busy} onAnalyze={evaluate} onApply={setDecisions}/>:<div className="builder"><section className="builder-catalog"><div className="catalog-controls"><div className="district-picker"><label htmlFor="target-district"><MapPin size={17}/>{copy.simulation.chooseDistrict}</label><select id="target-district" value={district} onChange={e=>setDistrict(e.target.value)}>{DISTRICTS.map(d=><option key={d.id} value={d.id}>{data.districts[d.id].name}</option>)}</select></div><p>{data.districts[district].profile}</p></div><div className="category-tabs" role="group" aria-label={t('noTransport')}><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>{t('all')}</button>{CATEGORIES.map(c=><button key={c.id} className={filter===c.id?'active':''} onClick={()=>setFilter(c.id)}><CategoryIcon id={c.id} size={16}/>{data.categories[c.id]}</button>)}</div><div className="initiative-grid">{MEASURES.filter(m=>filter==='all'||filter===m.category).map(m=>{
 const chosen=decisions.some(d=>d.measureId===m.id),prospective=m.scope==='city'?{measureId:m.id}:{measureId:m.id,districtId:district},valid=validate([...decisions,prospective],{partial:true});
 return <article className={`initiative ${chosen?'chosen':''}`} key={m.id}><div className="initiative-top"><span className="category-symbol" style={{color:COLORS[m.category],background:COLORS[m.category]+'12'}}><CategoryIcon id={m.category}/></span><span>{data.categories[m.category]}</span><strong>{m.cost}<small>{t('units')}</small></strong></div><h3>{data.measures[m.id].name}</h3><p>{data.measures[m.id].description}</p><div className="realized-effects">{Object.entries(m.effects).map(([k,v])=><span key={k} title={data.metrics[k]} className={v<0?'negative':''}>{data.metrics[k]} <b>{v>0?'+':''}{number(v*(8-m.lag)/8)}</b></span>)}</div><div className="effect-caption">{t('effect')}</div><div className="initiative-bottom"><span><Clock3 size={14}/> {m.lag} {t('quarter')}</span><button className={chosen?'selected-btn':'select-btn'} disabled={chosen||!valid.valid} onClick={()=>add(m)}>{chosen?<Check size={15}/>:<Plus size={15}/>} {chosen?t('selected'):t('choose')}</button></div>{!chosen&&!valid.valid&&<div className="blocked">{errorText(valid.errors[0])}</div>}</article>})}</div></section>
 <aside className="budget-aside"><div className="budget-card"><div className="budget-card-top"><span>{t('budget')}</span><span>100 {t('units')}</span></div><div className="remaining"><strong>{preview.remaining}</strong><span>{t('remaining')}</span></div><div className="budget-track">{decisions.map(d=>{const m=MEASURES.find(x=>x.id===d.measureId);return <i key={m.id} style={{width:m.cost+'%',background:COLORS[m.category]}}/>})}</div><div className="budget-sub"><span>{copy.simulation.spent}: {preview.cost}</span><span>{decisions.length}/5</span></div><h3>{t('decisions')}</h3><ol className="chosen-list">{Array.from({length:5},(_,i)=>{const d=decisions[i];if(!d)return <li className="empty-choice" key={i}><span>{i+1}</span>{t('emptySlot')}</li>;const m=MEASURES.find(x=>x.id===d.measureId);return <li key={i}><span className="choice-icon" style={{color:COLORS[m.category]}}><CategoryIcon id={m.category} size={17}/></span><div><strong>{data.measures[m.id].name}</strong><small>{d.districtId?data.districts[d.districtId].name:t('whole')} · {m.cost}</small></div><button className="icon-button" aria-label={`${t('remove')} ${data.measures[m.id].name}`} onClick={()=>setDecisions(decisions.filter((_,j)=>i!==j))}><Trash2 size={15}/></button></li>;})}</ol><div className="preview-score"><span>{t('preview')}</span><b>{number(preview.score)}</b><small>+{number(preview.score-BASELINE.score)}</small></div><button className="btn primary full" disabled={!check.valid||busy} onClick={evaluate}>{busy?t('analyzing'):t('next')}<ArrowRight size={18}/></button><button className="reset-button" onClick={()=>setDecisions([])}><RotateCcw size={14}/>{t('reset')}</button><p className="budget-rule">{t('selectHelp')}</p></div><div className="fairness-note"><Sparkles size={20}/><p>{t('fairnessText')}</p></div></aside></div>}
 </>;
}
function ArrowUpRightIcon(){return <ArrowRight size={16}/>;}
