// Optional page-level copy. Keep technical implementation details out of the UI.
export const UX_COPY = {
  kk: {
    nav: { home: 'Басты бет', map: 'Қала картасы', simulation: 'Шешімдер', scenarios: 'Сценарийлер', leaderboard: 'Командалар', methodology: 'Қалай есептеледі' },
    home: {
      eyebrow: 'Астана · Қаланы басқару симуляторы', title: 'Қаланың ертеңі —\nбүгінгі шешіміңіз.',
      description: '100 бірлік бюджет. 5 шешім. Әр ауданның өмір сапасына әсер етіңіз.',
      primary: 'Қаланы басқаруды бастау', secondary: 'Аудандарды зерттеу',
      insightTitle: 'Әр ауданға мүмкіндік', insight: 'Қаланың жалпы нәтижесімен бірге ең әлсіз ауданның жағдайы да есепке алынады.',
      budget: 'Бастапқы бюджет', decisions: 'Басқарушылық шешім', districts: 'Модельдегі аудан', horizon: 'Тоқсандық көкжиек',
    },
    map: {
      title: 'Астананы жақыннан таныңыз', description: 'Ауданды таңдап, оның басым мәселелері мен көрсеткіштерін көріңіз.',
      baseline: 'Бастапқы жағдай', projected: 'Сценарийден кейін', select: 'Ауданды таңдаңыз',
      districtScore: 'Ауданның өмір сапасы', population: 'Модельдегі халық үлесі', priority: 'Назар аударуды қажет етеді',
      mapNote: 'Оқу симуляторы: көрсеткіштер синтетикалық. Модель берілген бес ауданға негізделген.',
      schematicNote: 'Аудан аймақтары шартты түрде көрсетілген; ресми әкімшілік шекаралар емес.',
      startHere: 'Осы ауданға шара таңдау', allCity: 'Бүкіл қала',
    },
    simulation: {
      title: 'Бес шешіміңізді таңдаңыз', description: '100 бірлік бюджетпен қаланы жақсартыңыз. Әр таңдаудың құны мен әсерін салыстырыңыз.',
      chooseMeasure: 'Шараны таңдаңыз', chooseDistrict: 'Ауданды таңдаңыз', review: 'Сценарийді тексеріңіз', results: 'Нәтиже',
      add: 'Сценарийге қосу', remove: 'Алып тастау', remaining: 'Қалған бюджет', spent: 'Жұмсалған бюджет',
      cost: 'Құны', lag: 'Іске қосылу мерзімі', quarters: 'тоқсан', units: 'бірлік', cityScope: 'Бес ауданға да әсер етеді',
      districtScope: 'Бір ауданға әсер етеді', effect: 'Толық әсері', effectiveEffect: '8 тоқсанда іске асатын әсері',
      rules: 'Дәл 5 шара · Бір бағыттан ең көбі 2 · Қайталанбайды · Бюджеттен аспайды',
      evaluate: 'Нәтижені есептеу', analyze: 'AI талдауын алу', calculating: 'Сценарий есептелуде…', analyzing: 'AI шешімдеріңізді талдап жатыр…',
      budgetError: 'Бұл шараға бюджет жетпейді. Таңдауларыңыздың бірін өзгертіңіз.',
      incomplete: 'Нәтижені алу үшін дәл 5 шара таңдаңыз.',
      score: 'Astana Quality of Life Score', change: 'Бастапқы жағдаймен салыстырғанда',
      strengths: 'Күшті жақтары', risks: 'Тәуекелдер', recommendations: 'Ұсыныстар', consequences: 'Ықтимал салдары',
      save: 'Сценарийді сақтау', revise: 'Шешімдерді өзгерту', newScenario: 'Жаңа сценарий',
      modelAnalysis: 'Модель ережелеріне негізделген талдау', modelAnalysisNote: 'AI қолжетімсіз болғанда көрсетіледі. Есептелген нәтиже сақталады.',
      aiNote: 'Көрсеткіштерді модель есептейді. AI нәтижені түсіндіріп, ұсыныс береді.',
    },
    scenarios: {
      title: 'Сіздің сценарийлеріңіз', description: 'Таңдауларыңызды сақтап, нәтижелерін салыстырыңыз.',
      emptyTitle: 'Алғашқы сценарийіңізді жасаңыз', emptyBody: 'Сақталған шешімдер мен олардың нәтижелері осы жерде көрінеді.',
      create: 'Сценарий құру', name: 'Сценарий атауы', placeholder: 'Мысалы: Нұраға жаңа мүмкіндік',
      compare: 'Салыстыру', reopen: 'Ашу', delete: 'Жою', saved: 'Сценарий сақталды',
      compareHint: 'Салыстыру үшін екі сценарийді таңдаңыз.',
    },
    leaderboard: {
      title: 'Қала үшін ең жақсы шешімдер', description: 'Командалардың бірдей бастапқы деректермен алған нәтижелерін салыстырыңыз.',
      team: 'Команда', scenario: 'Сценарий', score: 'Өмір сапасы', budget: 'Шығын', improvement: 'Өсім',
      empty: 'Әзірге жарияланған нәтиже жоқ.', publish: 'Нәтижені жариялау',
    },
    methodology: {
      title: 'Әр балдың артында нақты есеп бар', description: 'Ережелер, бастапқы деректер және бағалау формуласы бәріне бірдей.',
      scale: 'Барлық көрсеткіш 0–100 шкаласымен өлшенеді. Жоғары мән — жақсы нәтиже.',
      horizon: 'Әсер 8 тоқсанға есептеледі. Іске қосылуы кеш шараның әсері осы мерзімде аздау болады.',
      formula: '70% — халық үлесімен өлшенген орташа балл, 30% — ең әлсіз ауданның баллы. 40-тан төмен әр көрсеткіш үшін 1 балл шегеріледі.',
      fairness: 'Мақсат — қаланың орташа нәтижесін жақсартып, әлсіз аудандарды назардан тыс қалдырмау.',
      dataNote: 'Бұл — хакатонның синтетикалық деректері. Олар Астананың нақты ағымдағы жағдайын сипаттамайды.',
      aiRole: 'AI есептелген нәтижелерді түсіндіреді. Score мен әсерлерді тек есептеу моделі анықтайды.',
    },
  },
  ru: {
    nav: { home: 'Главная', map: 'Карта города', simulation: 'Решения', scenarios: 'Сценарии', leaderboard: 'Команды', methodology: 'Методика' },
    home: {
      eyebrow: 'Астана · Симулятор управления городом', title: 'Город завтра —\nваше решение сегодня.',
      description: '100 единиц бюджета. 5 решений. Измените качество жизни в каждом районе.',
      primary: 'Начать управление', secondary: 'Изучить районы',
      insightTitle: 'Возможности для каждого района', insight: 'Результат учитывает и город в целом, и положение самого слабого района.',
      budget: 'Стартовый бюджет', decisions: 'Управленческих решений', districts: 'Районов в модели', horizon: 'Кварталов в горизонте',
    },
    map: {
      title: 'Познакомьтесь с Астаной ближе', description: 'Выберите район, чтобы увидеть его показатели и приоритетные проблемы.',
      baseline: 'Исходное состояние', projected: 'После сценария', select: 'Выберите район',
      districtScore: 'Качество жизни в районе', population: 'Доля населения в модели', priority: 'Требует внимания',
      mapNote: 'Учебный симулятор: показатели синтетические. Модель основана на пяти районах из задания.',
      schematicNote: 'Зоны районов показаны условно и не являются официальными административными границами.',
      startHere: 'Выбрать меру для района', allCity: 'Весь город',
    },
    simulation: {
      title: 'Выберите пять решений', description: 'Улучшите город с бюджетом 100 единиц. Сравнивайте стоимость и влияние каждого выбора.',
      chooseMeasure: 'Выберите меру', chooseDistrict: 'Выберите район', review: 'Проверьте сценарий', results: 'Результат',
      add: 'Добавить в сценарий', remove: 'Убрать', remaining: 'Осталось', spent: 'Потрачено',
      cost: 'Стоимость', lag: 'Срок запуска', quarters: 'кварт.', units: 'ед.', cityScope: 'Влияет на все пять районов',
      districtScope: 'Влияет на один район', effect: 'Полный эффект', effectiveEffect: 'Эффект за 8 кварталов',
      rules: 'Ровно 5 мер · До 2 из одного направления · Без повторов · В пределах бюджета',
      evaluate: 'Рассчитать результат', analyze: 'Получить AI-анализ', calculating: 'Рассчитываем сценарий…', analyzing: 'AI анализирует ваши решения…',
      budgetError: 'На эту меру не хватает бюджета. Измените одно из выбранных решений.',
      incomplete: 'Для расчёта результата выберите ровно 5 мер.',
      score: 'Astana Quality of Life Score', change: 'По сравнению с исходным состоянием',
      strengths: 'Сильные стороны', risks: 'Риски', recommendations: 'Рекомендации', consequences: 'Возможные последствия',
      save: 'Сохранить сценарий', revise: 'Изменить решения', newScenario: 'Новый сценарий',
      modelAnalysis: 'Анализ по правилам модели', modelAnalysisNote: 'Показывается, когда AI недоступен. Рассчитанный результат сохраняется.',
      aiNote: 'Модель рассчитывает показатели. AI объясняет результат и даёт рекомендации.',
    },
    scenarios: {
      title: 'Ваши сценарии', description: 'Сохраняйте решения и сравнивайте их результаты.',
      emptyTitle: 'Создайте первый сценарий', emptyBody: 'Здесь появятся сохранённые решения и их результаты.',
      create: 'Создать сценарий', name: 'Название сценария', placeholder: 'Например: Новые возможности для Нуры',
      compare: 'Сравнить', reopen: 'Открыть', delete: 'Удалить', saved: 'Сценарий сохранён',
      compareHint: 'Выберите два сценария для сравнения.',
    },
    leaderboard: {
      title: 'Лучшие решения для города', description: 'Сравнивайте результаты команд с одинаковыми исходными данными.',
      team: 'Команда', scenario: 'Сценарий', score: 'Качество жизни', budget: 'Расходы', improvement: 'Прирост',
      empty: 'Опубликованных результатов пока нет.', publish: 'Опубликовать результат',
    },
    methodology: {
      title: 'За каждым баллом — прозрачный расчёт', description: 'Единые правила, исходные данные и формула оценки для всех.',
      scale: 'Все показатели измеряются по шкале 0–100. Чем выше значение, тем лучше результат.',
      horizon: 'Эффект рассчитывается на 8 кварталов. Поздний запуск уменьшает реализованный эффект в этом периоде.',
      formula: '70% — средний балл с учётом населения, 30% — балл самого слабого района. Каждый показатель ниже 40 уменьшает результат на 1 балл.',
      fairness: 'Цель — улучшать городской результат, не оставляя слабые районы без внимания.',
      dataNote: 'Это синтетический датасет хакатона. Он не описывает реальное текущее состояние Астаны.',
      aiRole: 'AI объясняет рассчитанные результаты. Score и эффекты определяет только расчётная модель.',
    },
  },
  en: {
    nav: { home: 'Home', map: 'City map', simulation: 'Decisions', scenarios: 'Scenarios', leaderboard: 'Teams', methodology: 'Methodology' },
    home: {
      eyebrow: 'Astana · City management simulator', title: 'Tomorrow’s city.\nYour decisions today.',
      description: '100 budget units. 5 decisions. Shape quality of life in every district.',
      primary: 'Start governing', secondary: 'Explore districts',
      insightTitle: 'Opportunity in every district', insight: 'Your result reflects both the city as a whole and its weakest district.',
      budget: 'Starting budget', decisions: 'Policy decisions', districts: 'Model districts', horizon: 'Quarter horizon',
    },
    map: {
      title: 'Get to know Astana', description: 'Select a district to explore its indicators and most pressing needs.',
      baseline: 'Starting conditions', projected: 'After your scenario', select: 'Select a district',
      districtScore: 'District quality of life', population: 'Model population share', priority: 'Needs attention',
      mapNote: 'Learning simulator with synthetic indicators. The model uses the five districts in the task dataset.',
      schematicNote: 'District zones are illustrative and do not represent official administrative boundaries.',
      startHere: 'Choose a measure here', allCity: 'Entire city',
    },
    simulation: {
      title: 'Make your five decisions', description: 'Improve the city with 100 budget units. Compare the cost and impact of each choice.',
      chooseMeasure: 'Choose a measure', chooseDistrict: 'Choose a district', review: 'Review your scenario', results: 'Results',
      add: 'Add to scenario', remove: 'Remove', remaining: 'Remaining', spent: 'Spent',
      cost: 'Cost', lag: 'Time to launch', quarters: 'quarters', units: 'units', cityScope: 'Affects all five districts',
      districtScope: 'Affects one district', effect: 'Full effect', effectiveEffect: 'Effect within 8 quarters',
      rules: 'Exactly 5 measures · Up to 2 per category · No duplicates · Within budget',
      evaluate: 'Calculate results', analyze: 'Get AI analysis', calculating: 'Calculating your scenario…', analyzing: 'AI is reviewing your decisions…',
      budgetError: 'There is not enough budget for this measure. Adjust one of your choices.',
      incomplete: 'Choose exactly 5 measures to calculate your result.',
      score: 'Astana Quality of Life Score', change: 'Compared with starting conditions',
      strengths: 'Strengths', risks: 'Risks', recommendations: 'Recommendations', consequences: 'Possible consequences',
      save: 'Save scenario', revise: 'Revise decisions', newScenario: 'New scenario',
      modelAnalysis: 'Analysis from model rules', modelAnalysisNote: 'Shown when AI is unavailable. Your calculated result is preserved.',
      aiNote: 'The model calculates indicators. AI explains the result and suggests improvements.',
    },
    scenarios: {
      title: 'Your scenarios', description: 'Save your choices and compare their results.',
      emptyTitle: 'Create your first scenario', emptyBody: 'Your saved decisions and results will appear here.',
      create: 'Create scenario', name: 'Scenario name', placeholder: 'For example: New opportunities for Nura',
      compare: 'Compare', reopen: 'Open', delete: 'Delete', saved: 'Scenario saved',
      compareHint: 'Select two scenarios to compare.',
    },
    leaderboard: {
      title: 'Better decisions for the city', description: 'Compare team results from the same starting conditions.',
      team: 'Team', scenario: 'Scenario', score: 'Quality of life', budget: 'Spending', improvement: 'Improvement',
      empty: 'No results have been published yet.', publish: 'Publish result',
    },
    methodology: {
      title: 'Every point has a clear calculation', description: 'The same rules, starting data and scoring formula for everyone.',
      scale: 'All indicators use a 0–100 scale. A higher value means a better outcome.',
      horizon: 'Effects are calculated over 8 quarters. A later launch reduces the effect achieved within that period.',
      formula: '70% population-weighted average, 30% weakest district score. Each indicator below 40 deducts 1 point.',
      fairness: 'Improve the city overall while making sure weaker districts are not left behind.',
      dataNote: 'This is the hackathon’s synthetic dataset. It does not describe current real-world conditions in Astana.',
      aiRole: 'AI explains calculated results. Only the calculation model determines the Score and effects.',
    },
  },
};
