// Passwords and account identifiers belong in deployment configuration, not copy.
// District settings are illustrative scene directions, not factual city models.
export const V4_COPY = {
  kk: {
    auth: {
      title: 'Басқару кабинетіне кіру',
      description: 'Демонстрациялық аккаунтпен кіріп, симуляциядағы жұмысты жалғастырыңыз.',
      login: 'Кіру',
      email: 'Электрондық пошта',
      password: 'Құпиясөз',
      showPassword: 'Құпиясөзді көрсету',
      hidePassword: 'Құпиясөзді жасыру',
      signingIn: 'Кіру орындалуда…',
      logout: 'Шығу',
      role: 'Жұмыс рөлі',
      mayor: 'Әкім',
      manager: 'Қалалық басқарушы',
      roleNote: 'Аккаунт оқу симуляциясындағы рөлді анықтайды және нақты қызметтік мәртебені растамайды.',
      authRequired: 'Жұмысты жалғастыру үшін аккаунтқа кіріңіз.',
      invalidCredentials: 'Пошта немесе құпиясөз қате. Енгізілген деректерді тексеріңіз.',
      rateLimit: 'Кіру әрекеттері тым жиі қайталанды. Біраз уақыттан кейін қайталаңыз.',
      readOnly: 'Бұл бөлім тек көруге қолжетімді.',
      forbidden: 'Сіздің рөліңізге бұл әрекетті орындауға рұқсат берілмеген.',
      sessionExpired: 'Сессия аяқталды. Аккаунтқа қайта кіріңіз.',
      signedOut: 'Аккаунттан шықтыңыз.',
    },
    district: {
      workspace: 'Ауданның жұмыс кеңістігі',
      overview: 'Шолу',
      planning: 'Жоспарлау',
      beforeAfter: 'Дейін және кейін',
      presentation: 'Презентация',
      reportTitle: 'Аудан бойынша есеп',
      reportSubtitle: 'Таңдалған шаралар, олардың құны және аудан көрсеткіштеріне әсері.',
      impactTitle: 'Ауданға күтілетін әсер',
      localEffects: 'Аудандық шаралардың әсері',
      citywideEffects: 'Жалпықалалық шаралардың әсері',
      unchanged: 'Бұл сценарий ауданның есептік көрсеткіштерін өзгертпейді.',
      noLocalProjects: 'Бұл ауданға жергілікті шара таңдалмаған. Жалпықалалық шаралар оған әсер етуі мүмкін.',
      addMeasure: 'Ауданға шара қосу',
      saved: 'Аудан сценарийі сақталды.',
      sharedBudget: 'Барлық ауданға ортақ қала бюджеті',
      sceneNote: 'Аудан бейнесі шартты иллюстрация ретінде берілген. Нақты ғимараттар мен көшелер моделі емес.',
    },
    settings: {
      esil: 'Шартты көрініс: өзен жағасы, серуен жолы және биік ғимараттар.',
      almaty: 'Шартты көрініс: тығыз орналасқан көше кварталдары мен аула кеңістіктері.',
      saryarka: 'Шартты көрініс: қалыптасқан кварталдар, аласа және орта қабатты үйлер.',
      baikonur: 'Шартты көрініс: вокзал мен логистика тақырыбына негізделген кварталдар.',
      nura: 'Шартты көрініс: жаңа тұрғын үйлер, ашық жерлер және дамып келе жатқан көшелер.',
    },
  },
  ru: {
    auth: {
      title: 'Вход в кабинет управления',
      description: 'Войдите с демонстрационным аккаунтом, чтобы продолжить работу в симуляторе.',
      login: 'Войти',
      email: 'Электронная почта',
      password: 'Пароль',
      showPassword: 'Показать пароль',
      hidePassword: 'Скрыть пароль',
      signingIn: 'Выполняется вход…',
      logout: 'Выйти',
      role: 'Рабочая роль',
      mayor: 'Аким',
      manager: 'Городской управленец',
      roleNote: 'Аккаунт определяет роль в учебном симуляторе и не подтверждает реальный служебный статус.',
      authRequired: 'Войдите в аккаунт, чтобы продолжить.',
      invalidCredentials: 'Неверная почта или пароль. Проверьте введённые данные.',
      rateLimit: 'Слишком много попыток входа. Повторите немного позже.',
      readOnly: 'Этот раздел доступен только для просмотра.',
      forbidden: 'Вашей роли недоступно выполнение этого действия.',
      sessionExpired: 'Сессия завершена. Войдите в аккаунт снова.',
      signedOut: 'Вы вышли из аккаунта.',
    },
    district: {
      workspace: 'Рабочее пространство района',
      overview: 'Обзор',
      planning: 'Планирование',
      beforeAfter: 'До и после',
      presentation: 'Презентация',
      reportTitle: 'Отчёт по району',
      reportSubtitle: 'Выбранные меры, их стоимость и влияние на показатели района.',
      impactTitle: 'Ожидаемое влияние на район',
      localEffects: 'Эффект районных мер',
      citywideEffects: 'Эффект общегородских мер',
      unchanged: 'Этот сценарий не меняет расчётные показатели района.',
      noLocalProjects: 'Для района не выбраны местные меры. Общегородские меры могут влиять на его показатели.',
      addMeasure: 'Добавить меру для района',
      saved: 'Сценарий района сохранён.',
      sharedBudget: 'Единый городской бюджет для всех районов',
      sceneNote: 'Облик района показан условно. Это иллюстрация, а не модель реальных зданий и улиц.',
    },
    settings: {
      esil: 'Условная сцена: берег реки, прогулочная набережная и высотные здания.',
      almaty: 'Условная сцена: плотные уличные кварталы и дворовые пространства.',
      saryarka: 'Условная сцена: сложившиеся кварталы с малоэтажными и среднеэтажными домами.',
      baikonur: 'Условная сцена: кварталы, вдохновлённые вокзальной и логистической средой.',
      nura: 'Условная сцена: новое жильё, открытые территории и развивающаяся уличная сеть.',
    },
  },
  en: {
    auth: {
      title: 'Sign in to city management',
      description: 'Use a demo account to continue working in the simulator.',
      login: 'Sign in',
      email: 'Email',
      password: 'Password',
      showPassword: 'Show password',
      hidePassword: 'Hide password',
      signingIn: 'Signing in…',
      logout: 'Sign out',
      role: 'Working role',
      mayor: 'Mayor',
      manager: 'City manager',
      roleNote: 'Your account defines a role in the educational simulator and does not verify an official position.',
      authRequired: 'Sign in to continue.',
      invalidCredentials: 'The email or password is incorrect. Check your details.',
      rateLimit: 'Too many sign-in attempts. Please try again shortly.',
      readOnly: 'This section is available for viewing only.',
      forbidden: 'Your role does not permit this action.',
      sessionExpired: 'Your session has ended. Please sign in again.',
      signedOut: 'You have signed out.',
    },
    district: {
      workspace: 'District workspace',
      overview: 'Overview',
      planning: 'Planning',
      beforeAfter: 'Before and after',
      presentation: 'Presentation',
      reportTitle: 'District report',
      reportSubtitle: 'Selected measures, their costs and their impact on district indicators.',
      impactTitle: 'Expected district impact',
      localEffects: 'Effects of district measures',
      citywideEffects: 'Effects of citywide measures',
      unchanged: 'This scenario leaves the district’s calculated indicators unchanged.',
      noLocalProjects: 'No local measures are selected for this district. Citywide measures may still affect its indicators.',
      addMeasure: 'Add a district measure',
      saved: 'District scenario saved.',
      sharedBudget: 'One city budget shared by all districts',
      sceneNote: 'The district appearance is illustrative. It does not model actual buildings or streets.',
    },
    settings: {
      esil: 'Illustrative scene: a riverfront, a walking promenade and towers.',
      almaty: 'Illustrative scene: dense street blocks and courtyard spaces.',
      saryarka: 'Illustrative scene: established neighbourhoods with low and mid-rise housing.',
      baikonur: 'Illustrative scene: blocks inspired by railway stations and logistics areas.',
      nura: 'Illustrative scene: new housing, open land and a developing street network.',
    },
  },
};
