// Optimum labels are for an exhaustive, completed search within this model.
// Tool trace means visible calculator calls/results, not hidden model reasoning.
export const WHATIF_COPY = {
  kk: {
    title: '«Егер өзгертсек…» кеңесшісі',
    intro: 'Шешімдерді өзгерту салдарын сұраңыз. Көрсеткіштерді есептеу моделі анықтайды, AI нәтижені түсіндіреді.',
    inputLabel: 'Сценарий туралы сұрақ',
    placeholder: 'Мысалы: Нұрадағы мектептің орнына емхана таңдасақ, не өзгереді?',
    submit: 'Нұсқаны тексеру',
    working: 'Сценарий нұсқалары есептелуде…',
    toolTrace: 'Орындалған есептеулер',
    toolResult: 'Есептеу нәтижесі',
    proposedPlan: 'Ұсынылған сценарий',
    apply: 'Осы сценарийді қолдану',
    noChange: 'Ағымдағы шешімдер өзгерген жоқ.',
    invalidBudget: 'Ұсынылған нұсқа 100 бірлік бюджеттен асады. Құнын азайту қажет.',
    invalidPlan: 'Нұсқа симуляция ережелеріне сай емес. Көрсетілген шектеулерді ескеріп өзгертіңіз.',
    chatUnavailable: 'Кеңесші уақытша қолжетімсіз. Сценарийді қолмен өзгертіп, нәтижесін есептей аласыз.',
    shapley: 'Шепли әдісі бойынша үлес',
    shapleyNote: 'Шараны қосудың барлық ретіндегі орташа үлесі. Үлестердің қосындысы Score өзгерісіне тең.',
    optimum: 'Модельдегі ең жақсы нәтиже',
    optimumNote: 'Берілген деректер мен шектеулерге сай барлық бес шаралық сценарий арасындағы ең жоғары балл.',
    optimumGap: 'Ең жақсы нәтижеге дейінгі айырма',
    atOptimum: 'Модельдегі ең жоғары баллға жеттіңіз.',
  },
  ru: {
    title: 'Советник «Что, если…»',
    intro: 'Спросите о последствиях изменения решений. Модель рассчитывает показатели, AI объясняет результат.',
    inputLabel: 'Вопрос о сценарии',
    placeholder: 'Например: что изменится, если заменить школу в Нуре на поликлинику?',
    submit: 'Проверить вариант',
    working: 'Рассчитываем варианты сценария…',
    toolTrace: 'Выполненные расчёты',
    toolResult: 'Результат расчёта',
    proposedPlan: 'Предлагаемый сценарий',
    apply: 'Применить этот сценарий',
    noChange: 'Текущие решения не изменены.',
    invalidBudget: 'Предлагаемый вариант превышает бюджет 100 единиц. Нужно уменьшить стоимость.',
    invalidPlan: 'Вариант нарушает правила симуляции. Скорректируйте его с учётом указанных ограничений.',
    chatUnavailable: 'Советник временно недоступен. Вы можете изменить сценарий вручную и рассчитать результат.',
    shapley: 'Вклад по методу Шепли',
    shapleyNote: 'Средний вклад меры при всех порядках её добавления. Сумма вкладов равна изменению Score.',
    optimum: 'Лучший результат модели',
    optimumNote: 'Максимальный балл среди всех допустимых сценариев из пяти мер при этих данных и ограничениях.',
    optimumGap: 'Разница с лучшим результатом',
    atOptimum: 'Достигнут максимальный балл модели.',
  },
  en: {
    title: 'What-if advisor',
    intro: 'Ask how changing your decisions would affect the scenario. The model calculates the indicators; AI explains the result.',
    inputLabel: 'Question about your scenario',
    placeholder: 'For example: what changes if we replace the school in Nura with a clinic?',
    submit: 'Evaluate alternative',
    working: 'Calculating scenario alternatives…',
    toolTrace: 'Calculations performed',
    toolResult: 'Calculation result',
    proposedPlan: 'Proposed scenario',
    apply: 'Apply this scenario',
    noChange: 'Your current decisions are unchanged.',
    invalidBudget: 'The proposed alternative exceeds the 100-unit budget. Reduce its cost to continue.',
    invalidPlan: 'This alternative breaks the simulation rules. Revise it using the listed constraints.',
    chatUnavailable: 'The advisor is temporarily unavailable. You can still edit the scenario manually and calculate its result.',
    shapley: 'Shapley contribution',
    shapleyNote: 'A measure’s average contribution across every order of addition. Contributions sum to the change in Score.',
    optimum: 'Best result in the model',
    optimumNote: 'The highest score across all valid five-measure scenarios under these data and constraints.',
    optimumGap: 'Gap to the best result',
    atOptimum: 'You have reached the model’s maximum score.',
  },
};
